### ISSUE TITLE
Creating class diagrams

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#100]
### Problem

Post, Event, LFG, Search Bar, and Class Diagrams will be created for Recommendation. In this way, the sequential diagram will use these class diagrams to perform the relevant Use Cases.

### Solution

I will use Miro on the class diagram. When drawing class diagrams, I will specify the necessary attribute and operations/methods to provide system requirements. If we do not have the requirements to provide a use case, I will meet with the Team and update the instruments if found appropriate.

### Documentation

For now, I will write Comment as a screenshot. When everyone finishes their work, we will create a page for all class diagrams of Wiki.

### Additional notes

This work will be in the form of a group, I will specify the people who participate in the comment.

### Reviewers

Beyza Bektan

### Deadline

09.04.2023 - 23.59

**Comment by ahmetkudu** [comment]
We designed the Content interface in the screenshot below with [Erkam Kavak](https://github.com/bounswe/bounswe2023group6/wiki/Erkam-Kavak). Event, Post and LFG classes will receive inherentence from this interface. Thus, the common Attributes and Operations in these three classes will be defined once in the Content interface. After this interface was made, Taggable interface was done, but I did not take part in that study.

<img width="466" alt="Screenshot 2023-04-09 at 17 17 39" src="https://user-images.githubusercontent.com/74921213/230778001-63d4acf2-2cbc-460c-9d8f-5be27f85850e.png">

**Comment by ahmetkudu** [comment]
In the following screenshot, we completed the Search Bar and Recommendation Feed classes with Ömer Talip Akalın. According to the user's tags that have been logged into the system, Recommend Feed Class has lists for Content interface (Posts, Event, and LFG provide inheritance from this interface) and User class. Thus, users logged in to the system can also see events, posts, LFGs and other users as recommended. The lists are seen in a way that is closest to the creation dates of the relevant objects.

In the Search Bar Class, the user-based search history is formed by the Title for Taggable Content, Username in Username, Tags, Distance for Events, Company and Teams Searh Bar objects for (un)registered users.

<img width="341" alt="Screenshot 2023-04-09 at 17 12 29" src="https://user-images.githubusercontent.com/74921213/230779893-85d8043e-83bd-4505-94ac-70a74513a680.png">

**Comment by ahmetkudu** [comment]
@beyzabektan, could you review this issue?

**Comment by beyzabektan** [comment]
I reviewed the related parts of the diagram, compared with requirements/mockups, and it looks correct. So I can close this issue as completed.
