### ISSUE TITLE
Creating sequence diagrams

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#101]
### Problem

I will draw the Sequence Diagram to join the existing event of a user logged into the system and to be included in the existing LFG. This will show how the user will be provided with the server.

### Solution

I will use Miro to draw these diagrams. What is to be considered here is that attibutelas and operations are as defined in class diagrams.

### Documentation

For now, I will write Comment as a screenshot. When everyone finishes their work, we will create a page for all class diagrams of Wiki.

### Reviewers

Beyzanur Bektan

### Deadline

09.04.2023 - 23.59

**Comment by ahmetkudu** [comment]
Since it is similar to two diagrams, I will explain at one time: the user first selects all events or LFGs and selects what you want. After this selection, the server returns the ids of the relevant objects. After this stage, the number of participants in the event is less than the quota, or the number of people in the LFG is less than the number of maximum people required to participate in the relevant objects.

<img width="929" alt="Screenshot 2023-04-09 at 18 20 25" src="https://user-images.githubusercontent.com/74921213/230781740-fe8b7e0c-4cd9-4439-a1e0-9f5c0f65066b.png">

**Comment by ahmetkudu** [comment]
@beyzabektan, could you review this issue?

**Comment by beyzabektan** [comment]
Reviewed the relevant work, and closed this issue as completes since the task is performed properly.
