### ISSUE TITLE
Preparing Evaluation of Impact of Deliverables On Project Plan  For the Milestone Report

### ISSUE THREAD

**Issue by huscivi** [bounswe/bounswe2023group6#103]
### Problem

Evaluation of Impact of Deliverables On Project Plan section of milestone needs to be completed.

### Solution

I will complete the necessary part and add it to our page in google docs.

### Reviewers

Ömer Bahadıroğlu

### Deadline

09.04.2023

**Comment by huscivi** [comment]
The conclusion can be seen [here](https://docs.google.com/document/d/1agqm53xg2tf8lE3KdiC_pqAYyppXffQaI295Bhc_KCM/edit)

**Comment by huscivi** [comment]
@ohbahadiroglu  can you review and close this issue?

**Comment by ohbahadiroglu** [comment]
Since we reviewed it in the meeting yesterday, I will close the issue as done.
