### ISSUE TITLE
Resolving the shortcomings for the requirements part

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#109]
### Problem

According to the decision taken at [Meeting 14](https://github.com/bounswe/bounswe2023group6/wiki/Meeting-Notes-%2314---08.04.2023), the changes in requirements will be made. Thus, consistency will be provided in the studies carried out in Mock-up and UML.

### Solution

Some requirements are deleted, some new requirements are added, and others move to different sections. It was also ensured that the requirements were sorted correctly. In addition, Glossary was listed alphabetically.

### Documentation

requirements in wiki page

### Reviewers

Beyzanur Bektan

### Deadline

10.04.2023 - 23.59

**Comment by ahmetkudu** [comment]
To see the results of the study, [click](https://github.com/bounswe/bounswe2023group6/wiki/Requirements/_compare/d4de7096ab19b834b1304b90a5de44ef8356188b).

**Comment by ahmetkudu** [comment]
@beyzabektan, could you review this issue?

**Comment by beyzabektan** [comment]
Problem is solved and this issue is closed as completed.
