### ISSUE TITLE
Creating a project plan

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#110]
### Problem

Since the beginning of the project, we have prepared a project plan with [Hüseyin Çivi](https://github.com/bounswe/bounswe2023group6/wiki/Hüseyin-Çivi), [Erkam Kavak ](https://github.com/bounswe/bounswe2023group6/wiki/Erkam-Kavak)ve [Melih Portakal](https://github.com/bounswe/bounswe2023group6/wiki/Süleyman-Melih-Portakal) to show which member and when it was opened. Thus, we will be able to see the efforts of our members.

### Solution

First, we found a Gannt Chart Template for the Project Plan. Weeks consisted of 5 days, but we have increased the number of days to 7 because we worked on weekends. Then we outlined the project. These lines:

1. Project Conception and Initiation
2. Requirements
3. Use Case Diagram
4. Class Diagram
5. Sequence Diagram
6. Meeting Notes
7. Milestone

Later, starting from the oldest issues, we began to write the issue titles and who was assigned. We wrote in separate rows if an issue opened for more than one person. So everyone will be able to write their own working time and effort. 

We warned our team to enter the new issues to be opened until the Milestone delivery. In addition, we informed the group members about entering the color codes while entering their efforts. We said that there are color codes, three of which are burgundy color for high effort, orange for medium effort, and yellow color for low effort.

### Documentation

Milestone 1 Report

### Additional notes

As a result of the study, you will be able to find in Milestone 1 Report in the wiki page after delivering the milestone.  

### Reviewers

Beyzanur Bektan

### Deadline

10.04.2023 - 23.59

**Comment by ahmetkudu** [comment]
@beyzabektan, could you review this issue?

**Comment by beyzabektan** [comment]
Project plan of the group is created successfully as described under the solution title.
