### ISSUE TITLE
Filling the Responsibility Assignment Matrix

### ISSUE THREAD

**Issue by huscivi** [bounswe/bounswe2023group6#118]
### Problem

Responsibility Assignment Matrix(RAM) table have been structured and components of our project have been added. 
In this matrix, places about myself are empty.

### Solution

I need to fill in the places about myself in this matrix.

### Documentation

The table can be found [here](https://docs.google.com/spreadsheets/d/1TTC_MnJcbuhetxTDYepgyq6j4U04vXCMwoQQZIfuZfg/edit#gid=1831406299) as well as on our Milestone 1 report.

### Reviewers

Ömer Bahadıroğlu

### Deadline

10.04.2023

**Comment by huscivi** [comment]
@ohbahadiroglu Can you review and close this issue?

**Comment by ohbahadiroglu** [comment]
Seems fine.
