### ISSUE TITLE
Forming Individual Contribution Report for Milestone report 1

### ISSUE THREAD

**Issue by huscivi** [bounswe/bounswe2023group6#120]
### Problem

In order to complete Milestone Report 1, each team member must create an Individual Contribution Report and provide a link to it. Therefore, it is necessary for each team member to create their own individual report page.

### Solution

I will structure my individual milestone report according to the instructions provided by the staff, which are as follows:

- Member: Info about myself (name, group)
- Responsibilities: Overall description of the responsibilities that are assigned to me
- Main contributions: Overall description of my contributions to the project until
   Milestone. Provide the links to your work and related issues in your project repository,
-   Management related significant issues: My issues that contribute to the
  management of our software project (Please only lists the most-significant ones, we DO track all your issues separately.)
-   Additional information (optional): Further relevant information related to my contributions

### Documentation

You can reach the solution [here](https://github.com/bounswe/bounswe2023group6/wiki/Individual-Contribution-Report-H%C3%BCseyin-%C3%87ivi).

### Reviewers

Ömer Bahadıroğlu

### Deadline

10.04.2023

**Comment by huscivi** [comment]
@ohbahadiroglu can you review and close this issue?

**Comment by ohbahadiroglu** [comment]
Seems fine. I think it is ready for milestone report 1. Please do not forget to add your link at the end of the milestone report 1.
