### ISSUE TITLE
Forming an individual report for milestone 1

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#123]
### Problem

I will show all the work and contributions I have made up to Milestone 1.

### Solution

The solution should be structured as follows:

- Info about myself in the group
- Overall description of the responsibilities that are assigned to me
- Overall description of my contributions to the project until Milestone. Provide the links to my work and related issues in your project repository,
- My issues that contribute to the management of our software project.

### Documentation

[Ahmet Kudu under Individual Report in Milestone 1](https://github.com/bounswe/bounswe2023group6/wiki/Milestone-1-Report#d5-milestone-report)

### Reviewers

Beyzanur Bektan

### Deadline

10.04.2023 - 23.59

**Comment by ahmetkudu** [comment]
**Completion**: I started the study by opening a [Wiki Page](https://github.com/bounswe/bounswe2023group6/wiki/Individual-Contribution-Report---Ahmet-Kudu) and leaving a link in the Milestone 1 to reach this page.

**Comment by ahmetkudu** [comment]
@beyzabektan, could you review this issue?

**Comment by beyzabektan** [comment]
I checked the related page and it seems okay.
