### ISSUE TITLE
Filling the Project Plan and RAM

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#124]
### Problem

I will fill the Gannt Chart for Project Plan and Ram, which we created as group work in meeting 15. Thus, I will understand which tasks I took roles and how much time and effort I have completed.

### Solution

[Excel file link for the project plan chart](https://docs.google.com/spreadsheets/d/1q_JNNJ1hnr-IsJ_1Ch9FIU9Ifmb1DGb4uxo9m9_WbmQ/edit#gid=0)

[Excel file link for RAM chart](https://docs.google.com/spreadsheets/d/1TTC_MnJcbuhetxTDYepgyq6j4U04vXCMwoQQZIfuZfg/edit#gid=1831406299)

### Documentation

Milestone 1

### Reviewers

Beyzanur Bektan

### Deadline

10.04.2023 - 23.59

**Comment by ahmetkudu** [comment]
**Completion**: We made the project plan according to past studies. From the first week onwards, I put the issues and mentioned when I did them. You will color codes that are bordeaux color for high effort, orange color for medium effort, and yellow color is low effort.

**Comment by ahmetkudu** [comment]
@beyzabektan, could you review this issue?

**Comment by beyzabektan** [comment]
Related parts of the Gannt Chart and Ram are filled, so I can close this issue.
