### ISSUE TITLE
Creation and Organization of the Responsibility Assignment Matrix

### ISSUE THREAD

**Issue by Legervad** [bounswe/bounswe2023group6#127]
### Problem

* We are responsible for the creation a blueprint of Responsibility Assignment Matrix(RAM).

### Solution

* All issues are examined, and the corresponding rows are added to the RAM
* UML diagrams (including use case diagrams, class diagrams, and sequence diagrams) are examined and the necessary tasks are appended
* Meeting notes are added to the RAM so that the creators of the meeting notes can assign themselves as L
* Thought about all the meeting and the review that are done but not created any issue about, and added to the RAM
* Milestone related tasks are also added to the RAM
* Currently the Responsibility Assignment Matrix is settled, no additional change is required.
* Team member can follow the link provided and assign themselves one of the 5 status:

> Lead(L)
> Secondary(S)
> Contributor(C)
> Reviewer (R)
> None(N) 

### Documentation

The final product can be seen [at](https://docs.google.com/spreadsheets/d/1TTC_MnJcbuhetxTDYepgyq6j4U04vXCMwoQQZIfuZfg/edit#gid=1831406299)

### Additional notes

The RAM will be soon added to the wiki page.

### Reviewers

Erkam Kavak

### Deadline

10.04.2023 - Monday - 23.59

**Comment by Legervad** [comment]
The Responsibility Assignment Matrix has the following form

> ![image](https://user-images.githubusercontent.com/74266381/230898859-50bc1466-dfa0-4012-9fee-e4bb29f8ca69.png)

**Comment by Legervad** [comment]
@erkamkavak could you please review the issue?

**Comment by erkamkavak** [comment]
It looks like a comprehensive study. Nice job!
