### ISSUE TITLE
Fixing hyperlinks of the milestone

### ISSUE THREAD

**Issue by omertalib42** [bounswe/bounswe2023group6#136]
### Problem

The hyperlinks of the milestone has some bugs that we could not fix. If there's any time left, I'll try to fix them.

### Solution

Fix.

### Documentation

[Milestone 1](https://github.com/bounswe/bounswe2023group6/wiki/Milestone-1-Report#d5-milestone-report)

### Reviewers

Ömer Talip Akalın

### Deadline

10.01.2023 - 23.59

**Comment by smelihportakal** [comment]
i controlled every hyperlink and all of them work now
