### ISSUE TITLE
Creating Individual Contribution Report For Emre Türker

### ISSUE THREAD

**Issue by Legervad** [bounswe/bounswe2023group6#139]
### Problem

As part of the Milestone 1 assignment, all members must create an Individual Contribution Report.  The contents of the report will be as follows: 

> * Member: Info about myself (name, group)
> * Responsibilities: Overall description of the responsibilities that are assigned to me
> * Main contributions: Overall description of my contributions to the project until
>   milestone. Provide the links to your work and related issues in your project repository,
> * Management related significant issues: My issues that contribute to the
management of our software project (Please only lists the most-significant ones, we DO track all your issues separately.)
> * Additional information (optional): Further relevant information related to my contributions

### Solution

A page must be created and the link to that page must be placed under the milestone 1 page in the wiki section

### Documentation

[page](https://github.com/bounswe/bounswe2023group6/wiki/Individual-Contribution-Report-%7C-Emre-T%C3%BCrker)

### Reviewers

Beyzanur Bektan

### Deadline

10.04.2023 - Monday - 23.59

**Comment by beyzabektan** [comment]
The report has been properly written. I can now close this issue as completed.
