### ISSUE TITLE
Create a scenario about "Create Event"

### ISSUE THREAD

**Issue by nikodrates** [bounswe/bounswe2023group6#141]
### Problem

As a part of the requirements of Milestone1 team members should create scenarios.

### Solution

- I created a User named Ayşe Çağlayan.
- I created a story about what she wants to do.
- I specified her goals.
- I specified preconditions.
- I specified her actions.
- I specified Acceptance Criteria according to requirements.
- I created Mockups using Canva.

### Documentation

[Scenario](https://github.com/bounswe/bounswe2023group6/wiki/Create-Event-Scenario)

### Reviewers

@erkamkavak 

### Deadline

10.04.2023 - Monday - 23.59

**Comment by erkamkavak** [comment]
Excellent work! Now our project does not suffer from scenarios thank to this contribution.
