### ISSUE TITLE
Scenario about creating an event on mobile

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#143]
### Problem

The scenario will be made in accordance with the [Mock-up ](https://github.com/bounswe/bounswe2023group6/issues/54) I have made before. So, I will have described why the mock-up is done. 

### Solution

According to the user scenario that I will create, I will change the field in the mock-up I have made before.

### Documentation

Milestone 1 Report

### Additional notes

You can see the [result](https://github.com/bounswe/bounswe2023group6/wiki/Scenarios) of this task under the Scenarios and Mockups in the wiki sidebar.
Also, the completion of is [here](https://github.com/bounswe/bounswe2023group6/wiki/Scenario-about-Creating-Event-on-Mobile). 

### Reviewers

Beyzanur Bektan

### Deadline

10.04.2023 - 23.59

**Comment by erkamkavak** [comment]
It looks good.
