### ISSUE TITLE
Researching about world time API

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#151]
### Problem

Since the system we will create will be used worldwide, local clocks can be checked, especially when creating events. For this reason, users will be able to control local clocks from our system instead of searching on the Internet.

### Solution

Timezone will be entered to see the World Times on the website we will create. This timezone will be given as a parameter to the get method for requesting an api provided [https://timeapi.io/swagger/index.html](https://timeapi.io/swagger/index.html). This URL will respond a JSON format as the data, including time information. This clock information will be shown to the user on the website if a language code is correctly provided. 

### Documentation

Wiki page

### Reviewers

Beyzanur Bektan

### Deadline

01.05.2023 - 23.59

**Comment by ahmetkudu** [comment]
I watched some videos to use flask framework provided python programming language. 

- https://www.youtube.com/watch?v=c6YWgZkZzic&list=PLtTs2BKyiS4DLNLTVJ1ZtapaCn5wtjI_k
- https://www.youtube.com/watch?v=QLe58WLMlsg&list=PLIHume2cwmHfHLHWzndDnTTQUNRS3UbWq
- https://www.youtube.com/watch?v=QLe58WLMlsg&list=PLIHume2cwmHfHLHWzndDnTTQUNRS3UbWq

**Comment by ahmetkudu** [comment]
As can be seen in the screenshot below, timezone information will be obtained from the user as a parameter to use the get method. This get method will return to date time like shown below.

<img width="1096" alt="Screenshot 2023-05-01 at 13 51 50" src="https://user-images.githubusercontent.com/74921213/235443215-28b28d6a-d5ec-4d43-acf1-198e35279db2.png">

According to the date time information that returns from the get method, the user will need to provide the language code to use the following post method. Thus, the DateTime and LanguageCode information to be used in the post method are provided. As the final, I will be able to show world time shown below in the format of FrendlydateTime with a language determined by the user.

<img width="1084" alt="Screenshot 2023-05-01 at 13 52 13" src="https://user-images.githubusercontent.com/74921213/235443916-7b619dcc-3831-4182-a49a-4218a165e35d.png">

**Comment by ahmetkudu** [comment]
@beyzabektan, could you close this issue if it is okay?

**Comment by beyzabektan** [comment]
Looks like it has been a very useful research so I can close this issue.
