### ISSUE TITLE
Creating a Web UI

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#156]
### Problem

A web UI template will be held so that group members can show GET and Post Api Requests on a single website.

### Solution

After a template is found, the approval of the group members will be taken. What should be in this template will be a Landing Page at the beginning. When a button is pressed on the landing page, there will be a link to the form in which all Api requests appear. The button will be pressed for each api request. In addition, the header and the footer part will appear in all endpoints.

### Documentation

Wiki page

### Additional notes

Pull Request will be made and MERGE will be requested to be worked on the same web UI by every team member. 

### Reviewers

Beyzanur Bektan

### Deadline

01.05.2023 - 23.59

**Comment by ahmetkudu** [comment]
Click [here](https://fmtemplate.net/?pageName=template~template&bidx=1&pageMode=read&contentIdx=54) to reach the web uI template to be used. This template was arranged to be used web UI like:

Landing page is shown below

<img width="1470" alt="Screenshot 2023-05-01 at 14 39 34" src="https://user-images.githubusercontent.com/74921213/235446885-8f5bde18-e765-49cb-a91d-39780cc93734.png">

When clicking the Get Started button, you will be able to see all api request-related things that each of them will be done by team member separately

<img width="1457" alt="Screenshot 2023-05-01 at 14 40 00" src="https://user-images.githubusercontent.com/74921213/235446986-76ad5c33-69f6-444b-b3b2-19a7fb7124c5.png">

If you click WorldTime-Ahmet form on the web site, you will be able to see the below image. Header and footer was provided as base html. So those bars will be shown for all api requests. 

<img width="1469" alt="Screenshot 2023-05-01 at 14 43 50" src="https://user-images.githubusercontent.com/74921213/235447353-176d3fba-57b4-40ba-a416-c91db2cc91ec.png">

**Comment by ahmetkudu** [comment]
@beyzabektan, could you close this issue if it is okay?

**Comment by ahmetkudu** [comment]
Also, you can see the result on [the pull request](https://github.com/bounswe/bounswe2023group6/pull/155).

**Comment by beyzabektan** [comment]
The page has a nice interface and allows each team member to locate their API requests. Nice work!
