### ISSUE TITLE
Requesting API supporting the GET and POST methods to show world time

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#157]
### Problem

When the user enters [Timezone](https://timezonedb.com/time-zones) like Europe/Berlin through the website, Local Time should be seen on the website according to the language code like tr, en, de, fr, it and es provided by the user. Thus, the user will not have to search the Internet for World Time. 

### Solution

Timezone will be entered to see the World Time on the website we will create. This timezone will be given as a parameter to the get method for requesting an api provided https://timeapi.io/swagger/index.html. This URL describes how to use get or post methods. Get method that will be use will respond a JSON format as the data, including time information. This clock information will be shown to the user on the website if a language code is correctly provided. 

Post request also will be check by using the Postman. 

### Documentation

Wiki page

### Reviewers

Beyzanur Bektan

### Deadline

01.05.2023 - 23.59

**Comment by ahmetkudu** [comment]
I used a get method to request a [world time api](https://timeapi.io/swagger/index.html) on the 21st row in code below. It returns a json format including date time information. 

<img width="854" alt="Screenshot 2023-05-01 at 15 58 32" src="https://user-images.githubusercontent.com/74921213/235454703-e5179abd-28ed-4d84-bb07-0bd90f382259.png">

According to this date time information, I used a post method to show local time with the language provided by the user on the web site. 

<img width="941" alt="Screenshot 2023-05-01 at 16 03 06" src="https://user-images.githubusercontent.com/74921213/235455150-2f238291-808e-4380-92ac-fa177bfc78f9.png">

Output is like this. To be used the functionality, read the instructions that are in the web site. 

<img width="1032" alt="Screenshot 2023-05-01 at 16 06 33" src="https://user-images.githubusercontent.com/74921213/235455529-971b5260-74e3-43e2-95d9-3dae0ebf3dde.png">

**Comment by ahmetkudu** [comment]
When developing the api request, I checked the post method by using Postman. 

<img width="1089" alt="Screenshot 2023-05-01 at 16 21 12" src="https://user-images.githubusercontent.com/74921213/235457294-a0c57944-2337-4494-9b88-1e3239af0757.png">

**Comment by ahmetkudu** [comment]
@beyzabektan, could you close this issue if it is okay?

**Comment by ahmetkudu** [comment]
Also, you can see the result on [the pull request](https://github.com/bounswe/bounswe2023group6/pull/155).

**Comment by beyzabektan** [comment]
I checked all related parts and it seems fine. It was a good contribution to the Practice App.
