### ISSUE TITLE
Researching and implementing Steam API

### ISSUE THREAD

**Issue by erkamkavak** [bounswe/bounswe2023group6#160]
### Problem

For the practice app, I will use Steam API to pull the information about a game which is available at Steam. 

### Solution

Game name will be entered for searching in the practice app. Using steam API, all game ids will be pulled from [Steam All Apps](https://api.steampowered.com/ISteamApps/GetAppList/v2/) endpoint. I will find the id of the searched game from returned games. Using this id, I will pull the game information from [Steam Get Game Information](https://store.steampowered.com/api/appdetails?appids=420) endpoint. This returned game information will be showed in a new webpage.

### Reviewers

Ömer Talip Akalın

### Deadline

04.05.2023

**Comment by erkamkavak** [comment]
@ahmetkudu Can you review this issue?

**Comment by ahmetkudu** [comment]
Well done.
