### ISSUE TITLE
Creating database and login page in practice-app

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#168]
### Problem

We decided to create a database because some APIs do not support the post method. Such API's get method can be recorded to the Database if necessary. 

### Solution

Write the code required for Sqlalchemy. I will design the login screen. If the user is not registered in the system, the first will be registered. Then the user will be able to log in to the system. Thus, APIs can create records in Database with user-based login information.

### Documentation

Wiki page

### Reviewers

Erkam Kavak

### Deadline

05.05.2023 - 23.59

**Comment by ahmetkudu** [comment]
I used SqlAlchemy.ORM to get rid of SQL queries directly on the code; instead, you will be able to write any SQL queries with the idea of object class relationship. You can look at how to use [SqlAlchemy.ORM](https://www.youtube.com/watch?v=T6Q6bsv05To&list=PL4iRawDSyRvVd1V7A45YtAGzDk6ljVPm1&index=4) which is the video series that we followed during the coding. 

To see the activity on the database, you can install [Postgres](https://www.postgresql.org/download/). This helps us not to see database activities by using terminal. 

One another important thing about login page, every team member has to put '@login_required' under the decorator written by them as shown below. 
![Screenshot 2023-05-06 at 22 44 28](https://user-images.githubusercontent.com/74921213/236643781-4ad80cad-8e31-46c2-aef0-0aff28bdc9d8.png)

**Comment by ahmetkudu** [comment]
To run the database, you should be careful about the configuration of it. You can use any string values for them because they will be fixed when we deploy the practice app to AWS. 

![Screenshot 2023-05-06 at 22 47 57](https://user-images.githubusercontent.com/74921213/236643921-eaabaf57-036b-4a9a-bed2-52faa0bdd665.png)

**Comment by ahmetkudu** [comment]
Completion of this task is [here](https://github.com/bounswe/bounswe2023group6/pull/170).

**Comment by ahmetkudu** [comment]
@erkamkavak, could review this issue and close it kindly if it is okay?

**Comment by erkamkavak** [comment]
I reviewed the related parts and it seems good. Thank you for the contribution.
