### ISSUE TITLE
Keep the last world time api request

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#171]
### Problem

When some users want to create an event, they could want to the local time zone where they held the previous events. 

### Solution

When practice app users use the world time API request by providing necessary information and clicking the search button on the web UI, those necessary information, which are the parameters to be success API call, will be recorded on the database. So, when they get the Worldtime route again, they will be to see the last parameters again. 

### Documentation

Wiki page

### Reviewers

Erkam Kavak

### Deadline

07.05.2023 - 23.59

**Comment by ahmetkudu** [comment]
This is an example of how to use relationships on SQLAlchemy.ORM. 
![Screenshot 2023-05-07 at 01 20 00](https://user-images.githubusercontent.com/74921213/236648745-1035ed6f-0317-49ff-9795-6fe92b3f0bf4.png)

Completion of this task is [here](https://github.com/bounswe/bounswe2023group6/pull/172).

**Comment by ahmetkudu** [comment]
@erkamkavak, could you review this issue?

**Comment by erkamkavak** [comment]
Seems good to go. Nice work!
