### ISSUE TITLE
Change database structure

### ISSUE THREAD

**Issue by omertalib42** [bounswe/bounswe2023group6#179]
### Problem

We're not storing the credentials in the encrypted form right now. 

While it's understandable from the point that this is just experimental (and we were experimenting), it seems to prevent us from moving forward for the further stages. 

### Solution

Change stuff about login of the database.

### Reviewers

Erkam Kavak

### Deadline

10.05.2023 - 23.59

**Comment by ahmetkudu** [comment]
@omertalib42, if it is okay, could you close this issue kindly?

**Comment by omertalib42** [comment]
Cool.
