### ISSUE TITLE
Documentation of how to use World Time API

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#183]
### Problem

Update the GitHub wiki page with a description of the API and the functionality I introduced. So users of the practice-app will be able to use World Time API.  

### Solution

Desrice the usage of API with using markdown and screen shots. 

### Documentation

[Wiki page](https://github.com/bounswe/bounswe2023group6/wiki/The-Description-of-World-Time-API)

### Reviewers

Erkam Kavak

### Deadline

12.05.2022 - 23.59

**Comment by ahmetkudu** [comment]
Here is [the wiki page](https://github.com/bounswe/bounswe2023group6/wiki/The-Description-of-World-Time-API) not using swagger but markdown.

**Comment by ahmetkudu** [comment]
@erkamkavak, could you review this issue? If it okay, kindly close it.

**Comment by erkamkavak** [comment]
I have reviewed the documentation and it seems good.
