### ISSUE TITLE
Create Individual Contribution Report 

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#206]
### Problem

Below task depicted on moodle. Make sure that you provide all of them when preparing the documentation. 
- Their own name (as section name)
- Links to important issues (git issues) and wiki documentation related to practice application
- The name, route, description of utilized third party URIs
- The name, route, description of the created API functions
- Description of unit tests. You can include code fragments to illustrate.
- Sample calls: Show a transcript of a request and response for the API functions you used and that you provide. The transcript should include the request and the detailed response (headers, status code, json etc.)
- Any other significant work related to this release (such as Docker, AWS, DB, Framework)
- Describe any challenges you met during implementation.

### Solution

Open a new page on wiki and use markdown. 

### Documentation

[Wiki](https://github.com/bounswe/bounswe2023group6/wiki/Individual-Contribution-Report-2-%7C-Ahmet-Kudu)

### Additional notes

After creating a new page about this issue, leave the link just above the Documentation section. 

### Reviewers

Erkam Kavak

### Deadline

12.05.2023 - 23.59

**Comment by ahmetkudu** [comment]
[Here](https://github.com/bounswe/bounswe2023group6/wiki/Individual-Contribution-Report-Ahmet-Kudu) is a well-done job on this issue.

**Comment by ahmetkudu** [comment]
@erkamkavak, could you review this issue?

**Comment by erkamkavak** [comment]
> [Here](https://github.com/bounswe/bounswe2023group6/wiki/Individual-Contribution-Report-Ahmet-Kudu) is a well-done job on this issue.

I don't see anything on the link. Can you update it?

**Comment by ahmetkudu** [comment]
> > [Here](https://github.com/bounswe/bounswe2023group6/wiki/Individual-Contribution-Report-Ahmet-Kudu) is a well-done job on this issue.
> 
> I don't see anything on the link. Can you update it?

Thank you, check it out again.

**Comment by erkamkavak** [comment]
I have reviewed and it seems good. I am closing the issue.
