### ISSUE TITLE
Description of the basic functionality of practice-app

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#209]
### Problem

Describe the basic functionality of your project by using screenshots so that users of the web app can use the app efficiently. When you do that, be clear on

- how the web looks like 
- how signup, login, and logout are held
- how endpoints reached from the landing page

### Solution

Using screenshots, describe the usage of the web app

### Documentation

[Milestone-2-Report](https://github.com/bounswe/bounswe2023group6/wiki/Milestone-2-Report)

### Reviewers

Erkam Kavak

### Deadline

12.05.2023 - 23.59

**Comment by ahmetkudu** [comment]
You can see the completion of this issue [here](https://github.com/bounswe/bounswe2023group6/wiki/Description-of-the-basic-functionality-of-practice-app).

**Comment by erkamkavak** [comment]
It seems good and descriptive. I am closing the issue.
