### ISSUE TITLE
Create templates for issues and meeting notes

### ISSUE THREAD

**Issue by erkamkavak** [bounswe/bounswe2023group6#22]
- [x] Create template for feature issue and add it inside the repository
- [x] Create template for meeting notes and add it inside sidebar

**Comment by erkamkavak** [comment]
I have created the meeting notes template and added it inside sidebar. You can reach it from [Meeting Notes Template](https://github.com/bounswe/bounswe2023group6/wiki/Meeting-Notes-Template).

**Comment by ahmetkudu** [comment]
I have just created an issue template as you can see on [wiki  side bar](https://github.com/bounswe/bounswe2023group6/wiki/Issue-Template). It's fine. However, my another aim is to use this issue template when we click the 'New Issue' button in 'Issues' tab. According to the [this page](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository), it could be achieved. But I could not find this property in 'Setting' as you can see in the below image. @erkamkavak, Do you want to help me? 

<img width="751" alt="Screenshot 2023-03-11 at 23 20 50" src="https://user-images.githubusercontent.com/74921213/224509951-80c7867a-fc42-4e15-8933-43e89ea11d5a.png">

**Comment by erkamkavak** [comment]
>  But I could not find this property in 'Setting' as you can see in the below image. @erkamkavak, Do you want to help me?

I searched for it and I guess we need additional authorization to see or change this property from settings page. We may request this authorization. But there is another way to add issue template. We may add template as a yaml file into .github/ISSUE_TEMPLATE folder. We need to change md file to yaml file to be able to do this.

**Comment by erkamkavak** [comment]
I have added the issue template inside the repository. You can reach it from [here](https://github.com/bounswe/bounswe2023group6/blob/main/.github/ISSUE_TEMPLATE/task-issue.yaml). Since the template needs to be converted from markdown file to yaml file, there has been some minor changes. After the approval of @ahmetkudu, we can close the issue.

**Comment by erkamkavak** [comment]
Reopened because we need to add reviewer section to the issue template(after discussing it, we thought it will be better to have reviewers for issues).
