### ISSUE TITLE
Update the use case diagram w.r.t. the changes in the requirements

### ISSUE THREAD

**Issue by Legervad** [bounswe/bounswe2023group6#239]
### Problem

Having completed the refactoring of the requirements, the use case diagrams will require updates.

### Solution

Respective changes must be applied to the use case diagrams.

### Deadline

06.10.2023 - Friday - 23.59

**Comment by ahmetkudu** [comment]
This is done in [the backend meeting.](https://github.com/bounswe/bounswe2023group6/wiki/Meeting-Notes-%231-21.10.2023-%E2%80%90-Backend), and you can see the study on [the miro](https://miro.com/app/board/uXjVMVwkHtM=/).

**Comment by ahmetkudu** [comment]
I reopened this issue because of the wrong deleting.

**Comment by ohbahadiroglu** [comment]
@smelihportakal I remember that melih was taking care of this issue so it will be better to assign to him and close if it is done.

**Comment by Legervad** [comment]
Closing it
