### ISSUE TITLE
Update the class diagram w.r.t. the changes in the requirements

### ISSUE THREAD

**Issue by Legervad** [bounswe/bounswe2023group6#240]
### Problem

Having completed the refactoring of the requirements, the class diagram will require updates.

### Solution

Respective changes must be applied to the class diagram.

### Deadline

06.10.2023 - Friday - 23.59

**Comment by ahmetkudu** [comment]
This is done in [the backend meeting.](https://github.com/bounswe/bounswe2023group6/wiki/Meeting-Notes-%231-21.10.2023-%E2%80%90-Backend), and you can see the study on [the miro](https://miro.com/app/board/uXjVMVwkHtM=/).
