### ISSUE TITLE
Determine the back-end technologies

### ISSUE THREAD

**Issue by Legervad** [bounswe/bounswe2023group6#244]
### Problem

One of the three platforms that the application should be implemented is the back-end. The technologies that will be used in the back-end should be determined.

### Solution

Having formed the back-end team, the members should decide on the technologies they will be making use of during the project.

### Deadline

06.10.2023 - Friday - 23.59

**Comment by ohbahadiroglu** [comment]
We have decided to use Kotlin & Spring Boot in the backend team meeting. Further details are in the issue #254.
