### ISSUE TITLE
Decide the design of game page

### ISSUE THREAD

**Issue by smelihportakal** [bounswe/bounswe2023group6#249]
### Problem

We need to decide the fields, attributes and connections of game page.

### Solution

We will decide them by discussing together 

### Deadline

17.10.2023

**Comment by ahmetkudu** [comment]
The fields determined in the laboratory on 17.10.2023 are as follows. The fields here will be used commonly for all genres.

Genre -> Role-Playing Games (RGP), Strategy, Shooter, Sports and Racing, Fighting, and MOBA(Multiplayer Online Battle Arena) etc.
Platform -> Xbox, Computer, PS, and OnBoard etc
Avatar -> GameID, Name, and Description
Number of Players: Single, Multiple, and MMO(Massively Multiplayer Online-game)
Release Year
Universe -> Like Medieval
Mechanics -> Turn-Based, Chance-Based, etc.
Playtime -> how long a game lasts
Title
Map
