### ISSUE TITLE
Edit issue labels for teaming

### ISSUE THREAD

**Issue by omertalib42** [bounswe/bounswe2023group6#257]
### Problem

- The issue labels of the project are cool, but there's still quite a room for improvement as there will more teams, more tech, more ideas. There should be a refactor.

### Solution

Editing issue labels, adding some more, reconsiderations.

### Reviewers

Erkam Kavak

### Deadline

20.10.2023 - 23:59

**Comment by omertalib42** [comment]
We've discussed my updates now, and this one seems OK.

**Comment by erkamkavak** [comment]
Looks nice! Would be better if you don't close it before review.
