### ISSUE TITLE
Learn Flutter framework for the mobile

### ISSUE THREAD

**Issue by omertalib42** [bounswe/bounswe2023group6#258]
### Problem

We've decided to use Flutter for our project. Some people in the mobile team are somewhat familiar with the concepts, but there's a need to study more. This issue underlines the importance and the progress in the context.

### Solution

Learn Flutter.

### Documentation

https://docs.flutter.dev/

### Reviewers

Emre Sin

### Deadline

24.10.2023 - 23:59

**Comment by erkamkavak** [comment]
Each of us learned the flutter framework using its official documentation. We started implementing our mobile application. Thus we can close this issue.
