### ISSUE TITLE
Learn Kotlin & Spring Boot framework for the back-end

### ISSUE THREAD

**Issue by omertalib42** [bounswe/bounswe2023group6#259]
### Problem

We've decided to use Kotlin & Spring Boot for our project. Some people in the back-end team are somewhat familiar with the concepts, but there's a need to study more. This issue underlines the importance and the progress in the context.

### Solution

Learn Kotlin & Spring Boot.

### Documentation

https://kotlinlang.org/docs/getting-started.html

### Reviewers

Beyzanur Bektan, Süleyman Melih Portakal

### Deadline

24.10.2023 - 23:59

**Comment by ahmetkudu** [comment]
This is the [YouTube link](https://www.youtube.com/watch?v=9SGDpanrc8U) that I followed to learn Spring Boot. 
---
**Notes taken from the video:** 
 - _Controller_ layer will be used for resources of API. Within the Controller class, he annotated with the @RestController used for restful, and @RequestMapping(path = “api/v1/Students”) used for mapping localhost://8080/api/v1/Students
 ![Screenshot 2023-10-22 at 15 30 20](https://github.com/bounswe/bounswe2023group6/assets/74921213/46c238ad-c837-4265-a5cc-4fca2fbe49e1)

- Controller layer will talk _Service_ layer, which is responsible for business logic. Within the controller layer, he added StudentController with the parameter of StudentService, as you see in the below image. This is a much better approach for the N-Tier Design Pattern. 
![Screenshot 2023-10-22 at 15 35 44](https://github.com/bounswe/bounswe2023group6/assets/74921213/c07dffbc-09ff-425b-950a-456032b19df5)
![Screenshot 2023-10-22 at 15 41 24](https://github.com/bounswe/bounswe2023group6/assets/74921213/e009232f-d95e-4259-9aed-29019407582b)
On the above image, to resolve the error at the 17th row, we can add = new studentService. However, to avoid dependency injection we can use @Autowired like:
 ![Screenshot 2023-10-22 at 15 47 32](https://github.com/bounswe/bounswe2023group6/assets/74921213/9f2eeb06-582c-4c66-9fdf-bd407587f283)
So, we got the instantiation of Service with the help of the private final variable, and injected to the controller with the construction. We can resolve the above error by annotation using the 'component' like to have a 'bean', which means this has to be initiated.
![Screenshot 2023-10-22 at 15 49 04](https://github.com/bounswe/bounswe2023group6/assets/74921213/579338e1-9cf8-4bc4-8bd6-2b9daedfb17b)

- Before talking about _Repository_ layer, we map the Student class to the database Student table as shown below: 
![Screenshot 2023-10-22 at 16 09 40](https://github.com/bounswe/bounswe2023group6/assets/74921213/ddb33e46-0d77-4b73-ad62-3467e32f7dc9)
Before doing this, we had yet to get any fields in the Student table in the database. Finally, those fields were created using Hibernate. To be able to access the database, we create a repository interface extending JPARepository<TableName, UID_Type> as shown below:
![Screenshot 2023-10-22 at 16 23 31](https://github.com/bounswe/bounswe2023group6/assets/74921213/0b7f8c85-f74c-4354-aeda-24f653a7d375)
Finally, we can get records using the repository in the service when we did some changes in the service layer, as shown below:
![Screenshot 2023-10-22 at 16 28 24](https://github.com/bounswe/bounswe2023group6/assets/74921213/f3b6c7b8-e9d3-448f-ba0d-540e06c3c5c0)

**Comment by ahmetkudu** [comment]
Everyone learned Kotlin and Spring Boot. Also, @Legervad  explained to the backend team how we should use those in the meetings.
