### ISSUE TITLE
Implement the Change Password Endpoint

### ISSUE THREAD

**Issue by Legervad** [bounswe/bounswe2023group6#266]
### Problem

The users should be provided with a means to change their password when they wish to do so.

### Solution

The backend should provide an endpoint through which the frontend and mobil platforms can talk to it and thus users can change their passwords.

### Reviewers

_Ömer Bahadıroğlu_

### Deadline

31.10.2023 - Tuesday - 23.59

**Comment by ahmetkudu** [comment]
**Solution:**  To change the password, the user must log in to the system. Then, one old password (current password), one new password, and the same password due to confirmation shall be entered.

**Opened Branch Name:** backend/enchancement/change-password-#266
