### ISSUE TITLE
Branching and CI/CD configuration

### ISSUE THREAD

**Issue by omertalib42** [bounswe/bounswe2023group6#274]
### Problem

- Branching and CI/CD should be configurated as state in the lab report 3. 

### Solution

- Protect main branch, configure CI/CD, check possible linters & appropriate methods for future days.

### Additional notes

- This also depends on the setup of the front-end and back-end projects.

### Reviewers

Ömer Bahadıroğlu, Süleyman Melih Portakal

### Deadline

31.10.2023 - 23.59

**Comment by omertalib42** [comment]
CD is left for the other milestone.

**Comment by mustafakucuk-dev** [comment]
CI is implemented via github actions. (Docker build and push)
