### ISSUE TITLE
Example Endpoint Implementation for Test Purposes

### ISSUE THREAD

**Issue by ohbahadiroglu** [bounswe/bounswe2023group6#277]
### Problem

To validate and test our backend architecture (controller, service, repository layers), there is a necessity to implement an example endpoint. This endpoint will facilitate preliminary testing and validation, ensuring that each layer interacts cohesively and performs its designated function as expected. Having a working example is crucial for understanding the flow of data from the database to the client and ensuring the effectiveness of our layered architecture design.

### Solution

Implement an endpoint that retrieves data from a simple model in the database and returns it as JSON. The implementation should follow the layered architecture:

- Controller: An endpoint that handles HTTP requests and communicates with the service layer.

- Service: Do its business logic and communicate with repository layer.

- Repository: Communicates with the database, retrieves the data, and returns it to the service layer.

### Reviewers

Emre Türker

### Deadline

26.10.23 - Tuesday - 23.59

**Comment by erkamkavak** [comment]
Seems like development is completed. Can you close this issue
