### ISSUE TITLE
[Mobile] Separating validation and convertion into different layers in services

### ISSUE THREAD

**Issue by smelihportakal** [bounswe/bounswe2023group6#293]
### Problem
For this task, I have to solve two different problems: 
- Testing base service class for connecting to the backend.  
- Separating validation and converting into different layers in services

### Solution

I will create tests for base service and if there occurs any problem, I will solve them. 

### Reviewers

Süleyman Melih Portakal

### Deadline

31.10.2023

**Comment by erkamkavak** [comment]
For the first problem, PR #300 created.
