### ISSUE TITLE
Add Meeting Notes #4

### ISSUE THREAD

**Issue by smelihportakal** [bounswe/bounswe2023group6#32]
### Problem

The group had its fourth meeting at March 13th, between 22:00 and 23:55. The meeting notes must be published.

### Solution

I will organize the notes that i took and publish them.

### Additional notes

-This meeting was a sudden meeting so not everyone was able to attend.
-When the task is done, @umutdmr will check and close this issue.

### Deadline

15.03.2023 - Wednesday - 23.59

**Comment by Legervad** [comment]
Reviewed
