### ISSUE TITLE
Preparing a part of Milestone 1 Review : Evaluation of Tools and Processes

### ISSUE THREAD

**Issue by ohbahadiroglu** [bounswe/bounswe2023group6#346]
### Problem

To ensure that our team operates efficiently and effectively, there is a need for continuous evaluation of the tools, technologies and processes we have utilized throughout the project's lifecycle. Reflecting on these elements is crucial for identifying areas for improvement and for implementing best practices in future project phases.

### Solution

Compile a report that assesses the effectiveness, benefits, and limitations of each tool and process used by the team, including Discord, IntelliJ IDEA, PostgreSQL, Kotlin, Spring, DBeaver, and GitHub Projects.

### Documentation

milestone 1 deliverables link will be added

### Additional notes

Solution can be seen in the link above in the documentation link and also below as a comment.

### Reviewers

@ahmetkudu 

### Deadline

02.11.2023 - Thurdays - 21.00

**Comment by ohbahadiroglu** [comment]
Communication: Discord
Discord was an essential tool for our team's communication, giving us the ability to talk, video call, and message each other for both scheduled meetings and quick chats. We could make separate channels for different topics, which helped us stay organized. Since Discord doesn't have built-in tools for managing our projects, we added some extra tools to make everything work together. But overall, Discord was easy for everyone to use no matter what type of computer or phone they had.

IDE: IntelliJ IDEA
IntelliJ IDEA was our chosen software for writing and organizing our code, and it was particularly good because it had special features for Kotlin and Spring Boot, which are the main technologies we used. It could automatically complete parts of code for us and help us change large parts of it easily when needed. It also kept track of changes in our code. Although anyone could use the basic version for free, some of us used the paid version which had more helpful features for working with databases and code, but we had to consider the extra cost and effort to learn these features.

Database: PostgreSQL
PostgreSQL was very reliable for storing and handling our project's data, even when we had to do complicated things with it. It came with a lot of documentation, which helped us a lot, and there were many people using it who could help us when we got stuck. To really take advantage of everything PostgreSQL could do, we had to know a lot about databases, but it was worth it because it made our project's data management strong and able to grow.

Programming Language & Framework: Kotlin and Spring
Kotlin and Spring worked really well together for building the parts of our project that run on the server. Kotlin lets us write code that's easy to understand and shorter, which saves time. Spring has a lot of tools that do different things we needed, like making sure our app is secure and handles data properly. Even though it can take some time to learn how to set everything up with Spring, using Kotlin made it easier. So, they made a great combination for our project.

Database Tool: DBeaver
DBeaver was the tool we chose for working with our databases. It works with many different kinds of databases, which was perfect for us. The program's design made it simple to see our data, make changes, and do tests. It has a lot of different tools to use, and sometimes it was a bit too much, but it was really useful for managing our databases day to day.

Project Management: GitHub Projects
GitHub Projects helped us keep an eye on our work and organize our coding tasks. It's part of GitHub, so it worked well with the code we were already writing there. We used it like a board to move tasks around and see what we all were working on. It's not as full-featured as some other project management tools, but it was easy to use and helped us a lot.

**Comment by ohbahadiroglu** [comment]
@ahmetkudu can you please review and close this issue if everything is fine?

**Comment by ahmetkudu** [comment]
You are correct that the team effectively employed a combination of tools, including Discord for communication, IntelliJ IDEA for code development, PostgreSQL for data management, Kotlin and Spring for server-side operations, and GitHub Projects for project organization, enhancing their project's collaboration and efficiency.
