### ISSUE TITLE
Report the Evaluation of Tools and Processes - Frontend

### ISSUE THREAD

**Issue by beyzabektan** [bounswe/bounswe2023group6#348]
### Problem

For Milestone 1 deliverables, we need to evaluate the tools that we used during our development process. It is important for the potential enhancements in the future to ensure quality, efficiency, and compatibility of our software components.

### Solution

I will conduct an evaluation of React and VSCode which are the tools used in frontend part of our project.

### Reviewers

Halis Ayberk Erdem

### Deadline

02.11.2023 - Thursday - 21.00

**Comment by beyzabektan** [comment]
@nikodrates Could you please check the related section from [here](https://github.com/bounswe/bounswe2023group6/blob/develop/reports/m1_group6.md) and close this issue it's okay?

**Comment by nikodrates** [comment]
It seems okey.
