### ISSUE TITLE
Preparing a part of Milestone 1 Review: The Requirements Addressed in Milestone 1

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#349]
### Problem

Including requirements in a milestone report is crucial for transparency and accountability, as it allows our clients to see the direct correlation between project progress and the initial objectives, ensuring that the project stays on track and meets the specified criteria.

### Solution

Compare the requirements in the wiki with everything currently on the platform in deployment.

### Documentation

451 Milestone 1 Report

### Reviewers

Ömer Bahadıroğlu

### Deadline

02.11.2023 - 20.00

**Comment by ahmetkudu** [comment]
The following requirements will be added to the 451 Milestone 1
---
1.1.1.1 Guests shall provide their full name, a valid username, an unregistered, a valid password to sign up.
1.1.1.3 Users shall be able to login and logout to platform.
1.1.1.4 Users shall be able to reset, and change their passwords.
2.1.1 The platform shall use HTTPS protocol.
2.1.3 All sensitive user data, such as passwords, shall be encrypted using a salted hashing algorithm(such as SHA-256).
2.3.1 Language of the platform shall be English.
2.3.2 The web interface and the android application shall support the same functionality.
2.3.3 The platform should support UTF-8 character encoding.

**Comment by ahmetkudu** [comment]
@ohbahadiroglu, could you review this issue?

**Comment by ohbahadiroglu** [comment]
I reviewed and couldn't see any missing requirements had already addressed. Then it's done, closing the issue.
