### ISSUE TITLE
Document Event Requirements

### ISSUE THREAD

**Issue by Legervad** [bounswe/bounswe2023group6#35]
### Problem

Document Event Requirements that are to listed under system requirements

### Documentation

https://github.com/bounswe/bounswe2023group6/wiki/Requirements

### Additional notes

The results are subject to change

### Deadline

16.03.2023 - Thursday - 23:59

**Comment by Legervad** [comment]
Added the Event Requirements under the System Requirements section.

**Comment by beyzabektan** [comment]
Reviewed the related section and closed the issue as completed
