### ISSUE TITLE
[Frontend] Editing Game Page

### ISSUE THREAD

**Issue by beyzabektan** [bounswe/bounswe2023group6#359]
### Problem

We have a template game page but there need to be more fiels added to have a more proper game page.

### Solution

We will edit our game page design and add more editable fields.

### Deadline

14.11.2023 - 23.59

**Comment by beyzabektan** [comment]
Here is the modified version of the game page. I changed overall structure of the game page to improve design and add new fields like game rate functionality and page creation date.

<img width="640" alt="Ekran Resmi 2023-11-14 16 05 41" src="https://github.com/bounswe/bounswe2023group6/assets/123978913/b35f6fd1-4fbe-48ad-82ae-e569086e4648">

**Comment by huscivi** [comment]
It looks nice. I close this issue.
