### ISSUE TITLE
Documenting Recommendation - Forum Requirements

### ISSUE THREAD

**Issue by beyzabektan** [bounswe/bounswe2023group6#36]
### Problem

The Recommendation section and Forum section in the [Requirements](https://github.com/bounswe/bounswe2023group6/wiki/Requirements) should be documented.

### Solution

This task will be done according to the scratch prepared in the Meeting 4.

### Documentation

https://github.com/bounswe/bounswe2023group6/wiki/Requirements

### Deadline

16.03.2023

**Comment by beyzabektan** [comment]
@Legervad Could you please check the Recommendation and Forum parts of the [Requirements](https://github.com/bounswe/bounswe2023group6/wiki/Requirements) page and close this issue?

**Comment by Legervad** [comment]
Checked, it seems fine.
