### ISSUE TITLE
[Frontend] Editing Images on the Homepage

### ISSUE THREAD

**Issue by beyzabektan** [bounswe/bounswe2023group6#362]
### Problem

In our homepage, there are same pictures for all image fields. We need to change them.

### Solution

We will change the pictures in home page.

### Deadline

14.11.2023 - 23.59

**Comment by beyzabektan** [comment]
@huscivi could you close this issue if everything is fine?

**Comment by huscivi** [comment]
I have reviewed and it seems good. I am closing the issue.
