### ISSUE TITLE
[Backend] Changing in the registration - Milestone 1 Feedback

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#364]
### Problem

Username, password, confirmation password, and email field are sufficient to register. The others will be removed.

### Reviewers

@emresin12 

### Deadline

21.11.2023 - 23.59

**Comment by Legervad** [comment]
I will be working on this, later on.

**Comment by Legervad** [comment]
Those are taken care of in the #391 , and sensitive information like names-surnames are no more stored in the database, therefore I am closing the issue as completed.
