### ISSUE TITLE
[Frontend] Changing the location of uploading an image - Milestone 1 Feedback

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#365]
### Problem

It is not clear whether uploading the image in registration is optional or not. So, It has to be moved to the profile settings.

### Reviewers

Ahmet Kudu

### Deadline

21.11.2023 - 23.59

**Comment by Legervad** [comment]
Has not been done yet, will work on it. I am extending the deadline

**Comment by ahmetkudu** [comment]
I overlooked this issue. It was an issue that was first reported to the backend, but since the functionality was working, we thought the frontend team could solve it. @omertalib42, if it is okay for you, could you assign this issue to anyone?
