### ISSUE TITLE
[Backend] Doing a task sharing for implementing the profile page

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#367]
### Problem

A backend meeting will be held for all requirements under Requirements 1.1.2 Profile, those will be evaluated and distributed as tasks to backend members. 

### Additional notes

- Anyone who wishes will be able to start implementation early.
- Database tables will be created during the meeting.

### Deadline

12.11.2023 - 23.59

**Comment by Legervad** [comment]
This has been already done but forgotten to close.
