### ISSUE TITLE
Documenting the Questions About Requirements

### ISSUE THREAD

**Issue by emresin12** [bounswe/bounswe2023group6#37]
### Problem

Documenting the questions related to requirements in order to discuss them with the T.A

### Solution

The documentation will be done according to predetermined scheme in the meeting and it will include the questions that are discussed with the group.

### Deadline

16.03.2023

**Comment by smelihportakal** [comment]
As stated in #40 we have already checked the questions and explained some of them and sent them to TAe. So we can close this issue
