### ISSUE TITLE
Document the 'Accessibility & Availability' and 'Performance and Reliability' requirements

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#38]
### Problem

Document the 'Accessibility & Availability' and 'Performance and Reliability' part in the [Requirements](https://github.com/bounswe/bounswe2023group6/wiki/Requirements) so that we can present all requirements, the rest of them to be completed, in the next assistant meeting to elicit the requirements. 

### Solution

The solution will be achieved by looking up the [scratch](https://docs.google.com/document/d/1iSIr5YIwcGAGQxxcSxFYsV0xnc8BUettnlRPUugf0_s/edit) studied in the meeting 4(this is not documented yet), and using the markdown.

### Documentation

Requirements. To have exact point, look at non-functional requirements.

### Additional notes

Right now, I would not write down any glossaries in the [requirement](https://github.com/bounswe/bounswe2023group6/wiki/Requirements) because after we meet the assistant to discuss the requirement we prepared, there could be some changes to them. At the end of the elicitation meeting, I keep the glossaries about requirements written in the title of this issue.

### Reviewers

Beyzanur Bektan

### Deadline

15.03.2023 - Thuesday - 23.59

**Comment by ahmetkudu** [comment]
@beyzabektan, could you check the study completed for this issue and close this issue?

**Comment by beyzabektan** [comment]
@ahmetkudu I checked the related section and closed this issue as completed.
