### ISSUE TITLE
Completion of Introductions

### ISSUE THREAD

**Issue by omertalib42** [bounswe/bounswe2023group6#4]
As part of the homework, it is necessary for everyone to 
- Create a page of self-introduction
- Add references of that self-introduction page to sidebar and [Who We Are](https://github.com/bounswe/bounswe2023group6/wiki/Who-We-Are) page.
- Mark the related box below.

Please feel free to open, assign, edit, and complete an issue of your own with an approptiate labeling and a concise description to have a grasp of the procedure. You may also mention this issue -in your own issue- as a comment to make it more clear.
 
Current Status:

- [x] Umut Demir
- [x] Ömer Bahadıroğlu
- [x] Melih Portakal
- [x] Emre Türker
- [x] Erkam Kavak
- [x] Ahmet Kudu
- [x] Sena Özpınar
- [x] Hüseyin Çivi
- [x] Halis Ayberk Erdem
- [x] Beyzanur Bektan
- [x] Ömer Talip Akalın
- [x] Emre Sin

**Comment by huscivi** [comment]
Completed

**Comment by ohbahadiroglu** [comment]
#10

**Comment by ohbahadiroglu** [comment]
#10

**Comment by ohbahadiroglu** [comment]
#10
