### ISSUE TITLE
[Mobile] Post Page CRUD Operations and Service Connections

### ISSUE THREAD

**Issue by erkamkavak** [bounswe/bounswe2023group6#422]
### Problem

Currently, the post page lacks Create, Read, Update, and Delete (CRUD) operations and the service connections to support these operations. This absence hinders users in content management and disrupts the flow of data.

### Solution

Implementing full-fledged CRUD operations and necessary service connections on the post page will enhance user experience. This will ensure smoother and more effective data management and page interactions.

### Reviewers

Umut Demir

### Deadline

28.11.2023

**Comment by erkamkavak** [comment]
I have completed create, update, report pages and their service connections. Followings are the screenshots from the app: 

![image](https://github.com/bounswe/bounswe2023group6/assets/70749779/cc4af3cf-1de7-410c-bfd9-7854f9250d62)
![image](https://github.com/bounswe/bounswe2023group6/assets/70749779/da38c708-328e-47f1-a678-59e496cc972e)
![image](https://github.com/bounswe/bounswe2023group6/assets/70749779/910583cb-8d37-4501-a584-6c2de01b163a)
![image](https://github.com/bounswe/bounswe2023group6/assets/70749779/0dc3017e-ca55-4d1d-bda0-c85cdc4b1599)

Also service connections for upvote, downvote, delete added for both posts and comments.

**Comment by erkamkavak** [comment]
@umutdmr Can you review and close this issue?

**Comment by umutdmr** [comment]
Did you open a pull request for related branch?

**Comment by erkamkavak** [comment]
Yes, pr #453 is about this issue.
