### ISSUE TITLE
[Mobile] Display Related Posts on Game Page Description

### ISSUE THREAD

**Issue by erkamkavak** [bounswe/bounswe2023group6#429]
### Problem

The game page does not currently show related posts, which limits user engagement and does not provide additional context or community discussions about the game.

### Solution

Integrating related posts within the game page description can increase user engagement and provide a richer, more informative experience. This feature should dynamically display posts related to the game's content.

### Reviewers

Erkam Kavak

### Deadline

28.11.2023

**Comment by smelihportakal** [comment]
implemented and merged
