### ISSUE TITLE
[Mobile] Game Page Get Service Integration

### ISSUE THREAD

**Issue by erkamkavak** [bounswe/bounswe2023group6#430]
### Problem

Our game page is missing a connection to the backend service for fetching game details, which causes a lack of real-time data and affects content accuracy.

### Solution

Establishing a Get service for the game page to retrieve game details will ensure that the latest and most accurate information is displayed. It will also improve data consistency across the platform.

### Reviewers

Umut Demir

### Deadline

28.11.2023

**Comment by smelihportakal** [comment]
implemented and merged
