### ISSUE TITLE
Creating mockups for group and new group pop-up

### ISSUE THREAD

**Issue by huscivi** [bounswe/bounswe2023group6#48]
### Problem

I will create mock-up of group and group creation pop-up for mobile.

### Solution

Solution will be in our [canva link](https://www.canva.com/design/DAFdqmB816E/r1846X4h0OgaGwsCK54EsQ/edit?utm_content=DAFdqmB816E&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).

### Deadline

26.03.2023

**Comment by huscivi** [comment]
![mockup1](https://user-images.githubusercontent.com/113240964/230762914-14218357-a1f2-4103-9e3d-3caf442870ef.png)
![mockup2](https://user-images.githubusercontent.com/113240964/230762919-20c941ae-6faf-42e6-a8a0-d5bc658f04a4.png)

**Comment by huscivi** [comment]
@ohbahadiroglu  could you review my study?

**Comment by ohbahadiroglu** [comment]
These are well-designed mockups. It visualizes and provides the necessary software requirements in our project.
