### ISSUE TITLE
Taking Notes About the Feedbacks Given in the Customer Presentation 2

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#491]
### Problem

Negative and positive feedback given during the presentation will be recorded as notes. We will evaluate the negative feedback and try to fix it. Positive feedback will also serve as an example of the new features we will develop.

### Solution

Those who took notes during the presentation should write a comment here.

### Additional notes

This issue will be part of the milestone 2 report.

### Reviewers

Ömer Bahadıroğlu

### Deadline

31.11.2023 -23.59

**Comment by ahmetkudu** [comment]
- Games/Posts/Groups titles on the homepage should be Recommend Games/Recommend Posts/Recommend Groups.
- The customer is a little lost in the forum screen because she wants to see the comments for the same game.
- There was a problem with the post images appearing.
- The search layout should be more noticeable.
- Enlarge the category of the player number by adding the Team-Based category.
- There should be liked games section on the profile page.

**Comment by ohbahadiroglu** [comment]
Yes, these are the key points for the milestone 2 demo feedbacks. Thanks. Closing.
