### ISSUE TITLE
Preparing a part of Milestone 2 Review: Status of the Requirements

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#492]
### Problem

For all requirements, contact the backend, frontend, and mobile teams and show them as "completed" if the relevant requirement has been completed for all teams. Only show "In progress" if all teams have not completed but have started. If no team has started, show it as "not started". 

### Solution

Create a new wiki page and copy all the requirements there. Then, meet with the teams and state each requirement situation separately.

### Additional notes

[statuses of the requirements](https://github.com/bounswe/bounswe2023group6/wiki/Progress-according-to-requirements-for-Milestone-2-%E2%80%90-(not-started)-(in-progress)-(completed))

### Reviewers

Ömer Bahadıroğlu

### Deadline

1.12.2023 - 17.00

**Comment by ahmetkudu** [comment]
@ohbahadiroglu, could you review [statuses of the requirements](https://github.com/bounswe/bounswe2023group6/wiki/Progress-according-to-requirements-for-Milestone-2-%E2%80%90-(not-started)-(in-progress)-(completed))?

**Comment by ohbahadiroglu** [comment]
Done. thanks.
