### ISSUE TITLE
[Frontend][Backend] Fix CORS completely 

### ISSUE THREAD

**Issue by omertalib42** [bounswe/bounswe2023group6#502]
### Problem

This issue needs to be resolved completely.

### Solution

I will probably go over each codebase and deployment mechanism, edit (or possibly rewrite) them and fix this.

### Reviewers

Emre Türker

### Deadline

13.12.2023 - 23.59

**Comment by mustafakucuk-dev** [comment]
With the implementation of ssl certification and nginx reverse proxy, it is fixed.
