### ISSUE TITLE
[Backend] Creating endpoint returning the games rated as 4 or 5 by an user - Milestone 2 Feedback

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#506]
### Problem

"There should be liked games section on the profile page" was the feedback given the presentation of customer demo. So, users will be able to see their games that they liked. 

### Solution

I will create an endpoint providing above description. After creating the endpoint, I will be informing the frontend team to try this feature. 

### Documentation

In a pull request that will be created

### Additional notes

- Fix the bug relating to the image name not having game id
- Share screenshots to show that the task is done relating to the this issue.

### Reviewers

Ömer Bahadıroğlu

### Deadline

12.12.2023 - 23.59

**Comment by ahmetkudu** [comment]
Endpoint for Rated Games: Implemented a new endpoint to provide a list of games rated 4 or 5 by a user.
The endpoint allows users to retrieve highly-rated games based on their preferences.

Bug Fix: Image Names Include Game ID: Resolved a bug where image names were not including the game ID.
Ensured that image names now correctly include the associated game ID, improving consistency and resolving potential display issues.

![Screenshot 2023-12-11 at 22 06 13](https://github.com/bounswe/bounswe2023group6/assets/74921213/9f58f8e3-b1e2-4289-83fd-62b708611ef6)
![Screenshot 2023-12-11 at 22 06 51](https://github.com/bounswe/bounswe2023group6/assets/74921213/c4da378f-e0b9-46fe-9823-e6205eee892f)
![Screenshot 2023-12-11 at 22 07 20](https://github.com/bounswe/bounswe2023group6/assets/74921213/16df3e46-8c9c-4f34-8e89-67221ef0bc41)
![Screenshot 2023-12-11 at 22 11 35](https://github.com/bounswe/bounswe2023group6/assets/74921213/bc778a32-7d67-42fc-9d6a-d68087659a02)

**Comment by ahmetkudu** [comment]
@ohbahadiroglu, Could you review this?

**Comment by ohbahadiroglu** [comment]
reviewed and approved related pr thanks.
