### ISSUE TITLE
[Backend] Determine static values for the fields relating to a Game - Milestone 2 Feedback

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#508]
### Problem

"Enlarge the category of the player number by adding the Team-Based category." was the feedback given the presentation of customer demo. So, users will be able to add to depict that a game will be played with the teams. When we discuss this in the lab, we have decided that we should keep the values of all game fields as static. That helps us recommend a game to the users. 

### Solution

Explore the post entity in the backend code which has an enumaration holding the type of post. 

### Documentation

In a pull request that will be created

### Additional notes

Maybe, we can create new folder for values of the game fields because they are so much. 

### Reviewers

Ömer Bahadıroğlu

### Deadline

12.12.2023 - 23.59

**Comment by ahmetkudu** [comment]
Created a new kotlin file providing game fields with the static values:
![Screenshot 2023-12-12 at 10 31 05](https://github.com/bounswe/bounswe2023group6/assets/74921213/b1ea871e-6d82-4572-adfd-fe90c3a532d0)

Changes in game entity:
![Screenshot 2023-12-12 at 10 31 14](https://github.com/bounswe/bounswe2023group6/assets/74921213/a9dc905d-936b-48f7-9633-f99716fb7dd7)

Changes in GameDTO:
![Screenshot 2023-12-12 at 10 32 13](https://github.com/bounswe/bounswe2023group6/assets/74921213/0f6f0ec7-22b2-4209-92ec-d349cd2dcc15)

Changes in GameCreateRequest:
![Screenshot 2023-12-12 at 10 33 00](https://github.com/bounswe/bounswe2023group6/assets/74921213/71e376bd-de2f-4395-937f-1dbee6fce5f4)

Since static values can now be given for game fields, we will be able to make recommendations based on them.

**Comment by ahmetkudu** [comment]
@ohbahadiroglu, could you review this?

**Comment by ohbahadiroglu** [comment]
reviewed and approved related pr thanks.
