### ISSUE TITLE
[Mobile] LFG List/Create Page

### ISSUE THREAD

**Issue by erkamkavak** [bounswe/bounswe2023group6#518]
### Problem

Users currently cannot list or create 'Looking for Group' (LFG) entries, which limits the app's community interaction capabilities.

### Solution

We need to develop a dedicated LFG list/create page that allows users to view available groups and create new LFG posts. This should include form fields for necessary information and proper validation.

### Reviewers

Erkam Kavak

### Deadline

12.12.2023

**Comment by umutdmr** [comment]
@erkamkavak can you close this issue please?

**Comment by erkamkavak** [comment]
Reviewed the related pr and seems alright. Backend connections need to be added later. Nice job!
