### ISSUE TITLE
[Mobile] Post Add Category, Date, Tags

### ISSUE THREAD

**Issue by erkamkavak** [bounswe/bounswe2023group6#521]
### Problem

Posts are currently missing categories, dates, and tags, which makes organizing and searching content difficult.

### Solution

Updating the post creation and edit functionalities to include categories, dates, and tags will help in better organizing content and improving searchability.

### Reviewers

Süleyman Melih Portakal

### Deadline

12.12.2023

**Comment by erkamkavak** [comment]
[New branch](https://github.com/bounswe/bounswe2023group6/tree/mobile/enhancement/post-page-date-tags-catgs) created for this issue. After adding styling adjustments, I will open PR.

**Comment by erkamkavak** [comment]
Following changes are made in the related pr: 
- showing timeago in post card added
- category selection added to post creation
- tag selection added to post creation
- showing category, tag and timeago in post page added

Followings are the screenshots from the app: 
- Post card
![image](https://github.com/bounswe/bounswe2023group6/assets/70749779/5f73103f-a64c-454c-9ec0-76be122dde6e)

- Post creation
![image](https://github.com/bounswe/bounswe2023group6/assets/70749779/4f15cb0c-af77-4f02-9b4b-3a97197f59b5)

- Post page
![image](https://github.com/bounswe/bounswe2023group6/assets/70749779/77439d0e-c3cd-4a80-9881-810b183e3c58)

**Comment by umutdmr** [comment]
I have reviewed your issue and related pr. Works fine, good job!
