### ISSUE TITLE
[Mobile] Game Update Page

### ISSUE THREAD

**Issue by erkamkavak** [bounswe/bounswe2023group6#525]
### Problem

Game information cannot be updated efficiently due to the absence of a dedicated update page.

### Solution

A game update page is necessary for maintaining current and accurate game details. This page should include forms for updating game information and should validate the input data.

### Reviewers

Erkam Kavak

### Deadline

12.12.2023

**Comment by umutdmr** [comment]
@erkamkavak could you close this issue?
