### ISSUE TITLE
[Mobile] Game Missing Parts

### ISSUE THREAD

**Issue by erkamkavak** [bounswe/bounswe2023group6#526]
### Problem

The game rating feature is not currently connected to the backend, resulting in ratings not being saved or reflected.

### Solution

Establishing a connection between the game rating feature and the backend will ensure that user ratings are stored and displayed correctly. Other missing parts will also be added. 

### Reviewers

Erkam Kavak

### Deadline

12.12.2023

**Comment by smelihportakal** [comment]
merged and closed
