### ISSUE TITLE
Creating mock-up about event creation and viewing

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#54]
### Problem

When a user wants to create an event, the system must provide the necessary information. Thus, the user who wants to create an event can realize the event he thinks about without any problems. In addition, those who only want to participate in the events before the event occurs should be able to view all future events on the list view screen. While viewing these, he should be able to see the information he needs completely to avoid problems later.

### Solution

First of all, it is necessary to make sure that these two features are already provided by the requirements. If the current requirements are insufficient to support these features, we need to talk to the project owner and say we will enter new requirements that provide these two features. This process is significant for validation of requirements. Then you can start creating mock-ups using [canva](https://www.canva.com/).

### Documentation

Put the mock-ups below of the this issue

### Additional notes

Afterward, verification can be provided by creating user scenarios if needed later and it can be documented well in the wiki. 

### Reviewers

Beyzanur Bektan

### Deadline

27.03.2023

**Comment by ahmetkudu** [comment]
@beyzabektan, could you review my study? And close it please, if it is okay.

**Comment by beyzabektan** [comment]
It seems fine, I closed this issue as completed.
