### ISSUE TITLE
Updating Mock-Ups 

### ISSUE THREAD

**Issue by Legervad** [bounswe/bounswe2023group6#55]
### Problem

Revision the profile page mock-ups in that:

- users should be able to change the roles in their profile pages
- past events should be events and it should include both the upcoming events and the completed ones
- completed ones and upcoming events should be identifiable via a badge on them
- users' titles should be visible in their profile page

### Solution

- In the profile page edit section, users should be able to change their roles. To this end, a drop down list should be added to the UI in the mock up page.
- In the profile page "past events" section should be implemented in a way that not only the past events but also the upcoming events should be visible, and named as "events". Past events and upcoming events should be distinguishable, via the use of a badge-like UI component.
- User's titles such as "CEO at Peak"|"Developer at Trendyol"|"Mid-laner at SKT T1" should be visible in the profile page

### Reviewers

@beyzabektan 

### Deadline

02.04.2023 - Sunday - 23.59

**Comment by Legervad** [comment]
Before the update the mock up looks as follows

> ![image](https://user-images.githubusercontent.com/74266381/229296913-7487a64e-3b97-447b-b7de-e4f0d177a1da.png)
> ![image](https://user-images.githubusercontent.com/74266381/229296962-25aa6012-77d7-4ad0-9ac0-dd26e493728a.png)

**Comment by Legervad** [comment]
After the update is made

> ![image](https://user-images.githubusercontent.com/74266381/229297127-dbbcc8dd-d70c-49fb-8bb0-9e3d21a443ff.png)
> ![image](https://user-images.githubusercontent.com/74266381/229297281-0e24232a-b083-492c-ad7e-50cced3f8278.png)

**Comment by Legervad** [comment]
@beyzabektan could you please review the issue and close, if everything is OK?

**Comment by beyzabektan** [comment]
The relevant solution has been provided and the task is completed. So I can close this issue.
