### ISSUE TITLE
[Mobile] Implement Searchbar 

### ISSUE THREAD

**Issue by smelihportakal** [bounswe/bounswe2023group6#553]
### Problem

In our mobile app, we are in need of a search bar and related services. Once the backend is ready, we plan to implement the search bar functionality to enhance user navigation and overall user experience. This addition will significantly improve the app's usability and provide users with a more efficient way to find content.

### Deadline

25.12.2023

**Comment by mustafakucuk-dev** [comment]
Waiting for the implementation of backend endpoint
