### ISSUE TITLE
[Backend] Complete the Requirements Relating to the User

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#559]
### Problem

Awaiting requirements to be completed is the below:  
* 1.1.2.2 Users shall be able to view other profile pages which are visible. 
* 1.1.2.3 Users shall be able to delete their own profile pages. 
* 1.1.2.7 Users shall be able to edit their profile status (visibility) to others on the profile page. 
* 1.1.3.1.1 Users shall be able to view profiles of other users.
* 1.1.3.1.2 Users shall be able to follow other users. 
* 1.1.3.2.17 Users shall be able to filter post categories in the forum according to their types. 
* 1.1.3.3.2 Users shall be able to request updating game pages and adding/deleting details. 
* 1.1.3.3.7 Users shall be able to report game pages. 

### Reviewers

Emre Sin

### Deadline

19.12.2023 - 22.00

**Comment by ahmetkudu** [comment]
1.1.3.3.7 Users shall be able to report game pages. (completed)

![Screenshot 2023-12-17 at 10 23 45](https://github.com/bounswe/bounswe2023group6/assets/74921213/65077b54-221d-45c6-9890-507a3d4aaff1)

![Screenshot 2023-12-17 at 10 24 12](https://github.com/bounswe/bounswe2023group6/assets/74921213/f5d952b3-4861-48a5-a974-ce13432cbfff)

**Comment by ahmetkudu** [comment]
1.1.3.3.2 Users shall be able to request updating game pages and adding/deleting details. (completed)

**With the below controller, entity, request body, and service implementations, the owners of the game will be able to edit their games by requesting those changes to the admin. This request will be stored in the database with the requested_editing_names table name.**

Controller:
![Screenshot 2023-12-17 at 11 51 53](https://github.com/bounswe/bounswe2023group6/assets/74921213/176127d7-6a44-4d72-89ff-23f576f63fc2)

Request body:
![Screenshot 2023-12-17 at 11 52 57](https://github.com/bounswe/bounswe2023group6/assets/74921213/8253884f-d9f3-43b5-946a-959757dbfb4c)

Entity:
![Screenshot 2023-12-17 at 11 54 32](https://github.com/bounswe/bounswe2023group6/assets/74921213/06ff5e6d-b97c-4c3b-9802-8064e03718e9)

Service:
![Screenshot 2023-12-17 at 11 55 49](https://github.com/bounswe/bounswe2023group6/assets/74921213/c410dcd6-f8ed-4b0c-a6c1-9fdf9d5912ee)

**After the admin gets all requested editing games and sees the changes requested, the admin will be able to approve those changes to reflect everyone to make changes visible. Until the admin decides, all users will not see those changes, and the game owner cannot edit more than once. If the admin rejects the request, changes will be deleted from the database, and then the user can create another request. ** 

Controller:
![Screenshot 2023-12-17 at 12 19 50](https://github.com/bounswe/bounswe2023group6/assets/74921213/672b6d22-537f-4d40-8fe1-b7eb50d58943)


Service:
![Screenshot 2023-12-17 at 12 01 21](https://github.com/bounswe/bounswe2023group6/assets/74921213/7292184c-599b-408d-b444-a85a69f96cc7)
![Screenshot 2023-12-17 at 12 20 38](https://github.com/bounswe/bounswe2023group6/assets/74921213/752007a8-3772-4bb8-b802-e82193586c68)

**Comment by ahmetkudu** [comment]
@ohbahadiroglu, just so you know.

1.1.3.2.17 Users shall be able to filter post categories in the forum according to their types. (completed) 

Post Controller:
![Screenshot 2023-12-17 at 12 47 30](https://github.com/bounswe/bounswe2023group6/assets/74921213/66f0690f-2770-4191-a8ef-4f135da352cf)

Post Service:
![Screenshot 2023-12-17 at 12 48 04](https://github.com/bounswe/bounswe2023group6/assets/74921213/53b7a285-4767-47e3-a8f4-09d28cd9992a)

Post Repo:
![Screenshot 2023-12-17 at 12 48 20](https://github.com/bounswe/bounswe2023group6/assets/74921213/ca47b4f9-6ad4-461e-ba23-8be9cef8beab)

**Comment by ahmetkudu** [comment]
1.1.3.1.2 Users shall be able to follow other users. (completed)

**Users will be able to follow and unfollow others. Users cannot follow themselves.** 

User controller:
![Screenshot 2023-12-17 at 15 08 27](https://github.com/bounswe/bounswe2023group6/assets/74921213/638c80b8-f66e-4110-8734-fd4645a3804b)

User service:
![Screenshot 2023-12-17 at 15 21 04](https://github.com/bounswe/bounswe2023group6/assets/74921213/b7bfe01a-2486-491b-9b8b-164e7b8efef7)

User entity:
![Screenshot 2023-12-17 at 15 10 48](https://github.com/bounswe/bounswe2023group6/assets/74921213/7238b81d-820b-49bc-82cc-ac7cc8a4f791)

**Comment by ahmetkudu** [comment]
1.1.2.7 Users shall be able to edit their profile status (visibility) to others on the profile page. (completed)

When a user registers the system, the visibility of the user will be accurate. After the registration, the user will be able to change the visibility.

User Entity:
![Screenshot 2023-12-18 at 18 32 41](https://github.com/bounswe/bounswe2023group6/assets/74921213/3d7d589e-3864-4627-ab8a-10dd8695acdf)

User Service:
![Screenshot 2023-12-18 at 18 34 20](https://github.com/bounswe/bounswe2023group6/assets/74921213/43e111ef-a780-4a23-8ded-eb29554a938e)

UpdateUserRequest:
![Screenshot 2023-12-18 at 18 35 15](https://github.com/bounswe/bounswe2023group6/assets/74921213/b9649e61-eb26-4501-ad1d-726e7fd3ef0e)

**Comment by ahmetkudu** [comment]
1.1.2.2 Users shall be able to view other profile pages which are visible. (completed)

User Controller:
![Screenshot 2023-12-18 at 19 12 46](https://github.com/bounswe/bounswe2023group6/assets/74921213/3239e2a2-56c2-4734-a2a8-8b18a2511ddb)

User Service:
![Screenshot 2023-12-18 at 19 13 53](https://github.com/bounswe/bounswe2023group6/assets/74921213/7df48e67-cb3c-4550-9dfb-8d230d3df936)

User Repository:
![Screenshot 2023-12-18 at 19 14 51](https://github.com/bounswe/bounswe2023group6/assets/74921213/dfa20de4-fcd2-4416-830f-08b4a319afe3)

**Comment by ahmetkudu** [comment]
1.1.3.1.1 Users shall be able to view profiles of other users. (completed by Emre Türker before)

**Comment by ahmetkudu** [comment]
1.1.2.3 Users shall be able to delete their own profile pages. (completed)

When a user deletes their profile, the session will be out. 

User Controller:
![Screenshot 2023-12-18 at 21 54 22](https://github.com/bounswe/bounswe2023group6/assets/74921213/4a2556f2-379a-4c85-8ddf-9cf98328a039)

User Service:
![Screenshot 2023-12-18 at 22 11 01](https://github.com/bounswe/bounswe2023group6/assets/74921213/f3ca28d2-cbe2-4d57-ac6e-8531000b1037)

**Comment by ahmetkudu** [comment]
@emresin12, could you review this? Kindly close it if it is okay.

**Comment by emresin12** [comment]
It seems fine so I'm closing it 👍🏼
