### ISSUE TITLE
Creating the Use Case Diagram for the Profile Page (Mobile-Web)

### ISSUE THREAD

**Issue by Legervad** [bounswe/bounswe2023group6#56]
### Problem

- The profile page part of the project's use case diagram must be completed.

### Solution

- The task includes the use of both "includes" and "extends" types of relations. The difference between those two keywords must be considered and the diagram should be designed accordingly.

### Documentation

[the link to the miro page]()

### Reviewers

Erkam Kavak

### Deadline

02.04.2023 - Sunday - 20.00

**Comment by Legervad** [comment]
My work on the use case of the Profile Page:

> ![image](https://user-images.githubusercontent.com/74266381/229852381-f9b2b3cf-d457-46c6-a01a-cb99fef745b3.png)

**Comment by Legervad** [comment]
@erkamkavak could you review my work please?

**Comment by erkamkavak** [comment]
Reviewed and closed as completed.
