### ISSUE TITLE
Updating mock-ups of "Forum" and "Create Post" pages

### ISSUE THREAD

**Issue by beyzabektan** [bounswe/bounswe2023group6#57]
### Problem

In the previous version of the forum page, users were not allowed to filter posts according to their types. However, users shall be able to select the post type that they want to view while surfing on the forum. Also, users shall be able to specify the type of the post they are creating.

### Solution

- A filtering option should be added to the forum page that makes user activities on the forum more efficient. 
- A type selection part should be added to the post creation page.

### Additional notes

Relevant link is here for [web](https://www.canva.com/design/DAFdqnceS1g/w6aX4gu2bvV_ONFZYhnPzg/edit?utm_content=DAFdqnceS1g&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) and [mobile](https://www.canva.com/design/DAFdqmB816E/r1846X4h0OgaGwsCK54EsQ/edit?utm_content=DAFdqmB816E&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).

### Reviewers

Emre Türker

### Deadline

01.04.2023 23.59

**Comment by beyzabektan** [comment]
### Old and new versions of the mock-ups related to this problem:

![1](https://user-images.githubusercontent.com/123978913/229306872-3bab24b5-d5f1-4296-bfcd-44ecf1a3290e.png)
![2](https://user-images.githubusercontent.com/123978913/229306878-1235e628-c44c-4d32-afae-1bc7cd143b5c.png)

**Comment by Legervad** [comment]
Seems fine.
