### ISSUE TITLE
Revising mock-ups for group finding and group creation (mobile)

### ISSUE THREAD

**Issue by huscivi** [bounswe/bounswe2023group6#59]
### Problem

Adding more properties to the mock-ups and fixing some problems.

### Solution

Those changes will be done;

- To remove the group creation part from being a pop-up and design it as a separate page
- Adding language, platform, game information while creating a group
- Make group photos not unique to the group and sync them to the profile photo of the person who created the group

### Documentation

https://www.canva.com/design/DAFdqmB816E/r1846X4h0OgaGwsCK54EsQ/edit?utm_content=DAFdqmB816E&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

### Deadline

02.04.2023

**Comment by huscivi** [comment]
![mockup1](https://user-images.githubusercontent.com/113240964/230762957-6a8d31d7-be38-4004-963f-881b45f6f1aa.png)
![mockup2](https://user-images.githubusercontent.com/113240964/230762959-a3bc7b2c-b651-4801-809c-009465e575f6.png)

**Comment by huscivi** [comment]
@ohbahadiroglu could you review my study?

**Comment by ohbahadiroglu** [comment]
Your revision about mockups seems fine to me. It visualizes and provides the necessary software requirements in our project. I will close the issue.
