### ISSUE TITLE
[Backend] Changes and Requests Given by Mobile and Frontend Teams

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#596]
### Problem

Complete some of the changes and requests below given by mobile and frontend teams.

- Genre and platform should be selected one or more. 
- Get how a user rated a game. 
- A user should rate a game again. Right now, the user is rating a game once. 
- The GetGames endpoint should get a response containing only approved games. 
- When we get a response relating to the user, admin information should be in this response to direct the user to the admin panel. 
- Change the look of game field values as camel case since there is a problem with capital letters on the frontend team.

### Reviewers

Ömer Bahadıroğlu

### Deadline

25.12.2023 - 23.59

**Comment by ahmetkudu** [comment]
Genre and platform should be selected one or more. (completed)

Game entity:
![Screenshot 2023-12-23 at 23 16 21](https://github.com/bounswe/bounswe2023group6/assets/74921213/413c7cb3-6982-45a8-9ad9-5e370f572f3b)

RequestEditingGame entity:
![Screenshot 2023-12-23 at 23 17 56](https://github.com/bounswe/bounswe2023group6/assets/74921213/e9a53625-d697-45cd-8d6a-301d4c01537c)

**Comment by ahmetkudu** [comment]
The GetGames endpoint should get a response containing only approved games. (completed)

Game service:
![Screenshot 2023-12-23 at 23 54 28](https://github.com/bounswe/bounswe2023group6/assets/74921213/2a2c8591-8a98-4b7e-a92a-df67420eeef2)

**Comment by ahmetkudu** [comment]
When we get a response relating to the user, admin information should be in this response to direct the user to the admin panel. (completed)

Added a related field into the sections below.
![Screenshot 2023-12-24 at 08 41 34](https://github.com/bounswe/bounswe2023group6/assets/74921213/a1e21f9b-81e5-4d07-a6f3-2985be793f15)

![Screenshot 2023-12-24 at 08 42 28](https://github.com/bounswe/bounswe2023group6/assets/74921213/4cc44a79-1439-42ef-ac15-9bac063b2ce9)

**Comment by ahmetkudu** [comment]
A user should rate a game again. Right now, the user is rating a game once. (completed)

Game service:
![Screenshot 2023-12-24 at 09 02 05](https://github.com/bounswe/bounswe2023group6/assets/74921213/9bb7e49d-e24e-4a4a-9b69-a77efa408f84)

**Comment by ahmetkudu** [comment]
Get how a user rated a game. (completed)

Game Controller:
![Screenshot 2023-12-24 at 09 35 03](https://github.com/bounswe/bounswe2023group6/assets/74921213/1eb1bd15-9b9b-4c1f-97b5-d68bb62aac28)

Game Service:
![Screenshot 2023-12-24 at 09 36 17](https://github.com/bounswe/bounswe2023group6/assets/74921213/491c7a46-ba2c-464c-923d-d1180a0822e3)

**Comment by ahmetkudu** [comment]
Change the look of game field values as camel case since there is a problem with capital letters on the frontend team. (completed)

![Screenshot 2023-12-24 at 09 59 06](https://github.com/bounswe/bounswe2023group6/assets/74921213/61681994-db75-4492-b1f5-8f2bab54e673)

**Comment by ahmetkudu** [comment]
@ohbahadiroglu, could you review this issue?

**Comment by ohbahadiroglu** [comment]
Well documented, thanks. Related PR is approved. So, closing this issue.
