### ISSUE TITLE
Revising mockups for Homepage (web,mobile)

### ISSUE THREAD

**Issue by ohbahadiroglu** [bounswe/bounswe2023group6#61]
### Problem

Adding more properties to the mock-ups ([web](https://www.canva.com/design/DAFdqnceS1g/w6aX4gu2bvV_ONFZYhnPzg/edit?utm_content=DAFdqnceS1g&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton), [mobile](https://www.canva.com/design/DAFdqmB816E/r1846X4h0OgaGwsCK54EsQ/edit?utm_content=DAFdqmB816E&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)) and fixing some problems discussed in the [meeting #6](https://github.com/bounswe/bounswe2023group6/wiki/Meeting-Notes-%236-24.03.2023).

### Solution

Discussed changes or improvements that will be applied to the mock-ups:

- Make sections scrollable to visualize the up and down movement.
- Enlarge the header for events.
- Add the number of participants and tags for events.
- Add the date and relevant tags to posts.
- Add the number of participants, group name or title, and game name for groups.
- Separate the feed view into sections for events, followed users, groups, and posts for mobile devices.

### Documentation

Homepage-mockups canva link [web](https://www.canva.com/design/DAFdqnceS1g/w6aX4gu2bvV_ONFZYhnPzg/edit?utm_content=DAFdqnceS1g&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) , [mobile](https://www.canva.com/design/DAFdqmB816E/r1846X4h0OgaGwsCK54EsQ/edit?utm_content=DAFdqmB816E&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

### Additional notes
 New versions of the homepage mockups can be displayed in the comments of the issue, when the work is done.
#### WEB
![homepage-web](https://user-images.githubusercontent.com/93478016/229353735-f465e985-0796-4534-94dc-1ba1ec9c11e4.png)
#### MOBILE
![homepage-mobil](https://user-images.githubusercontent.com/93478016/229353731-b6903a48-40bd-45a8-b250-895eaa2d53a9.png)

 

### Reviewers

Ömer Talip Akalın

### Deadline

02.04.2023 - 23.59

**Comment by ohbahadiroglu** [comment]
## NEW VERSION OF THE HOMEPAGE MOCKUPS
### WEB
![homepage-web](https://user-images.githubusercontent.com/93478016/229380918-62c6d0a0-9dbb-47ed-a160-e7c0b812bbc0.png)
### MOBILE
![homepage-mobile](https://user-images.githubusercontent.com/93478016/229380919-35f02bb1-501e-45a7-a9fa-11145b936145.png)

**Comment by ohbahadiroglu** [comment]
@omertalib42 
Could you please review new versions of the homepage mockups? If everything is fine you can close the issue.

**Comment by omertalib42** [comment]
Looking good to me.
