### ISSUE TITLE
Creating a use-case diagram for Personal Feed on the Homepage (web,mobile)

### ISSUE THREAD

**Issue by ohbahadiroglu** [bounswe/bounswe2023group6#62]
### Problem

To ensure a clear and concise representation of the user interactions with our platform, I need to create a use case diagram for the homepage. While diagramming homepage and related functionalities such as recommended posts, events, groups, people to follow and a navigation bar, I will update the relevant [requirements](https://github.com/bounswe/bounswe2023group6/wiki/Requirements) in the wiki if necessary.

### Solution

Solution will be created by examining [requirements](https://github.com/bounswe/bounswe2023group6/wiki/Requirements) - 1.2.1 Recommendations -
A registered user shall be able to see recommended Users, LFGs, Posts, Events in their personal feed. Guest users shall be able to see recommendations (LFGs, Posts, Events, Users) recently appeared in the platform.
![Screenshot from 2023-04-06 19-52-44](https://user-images.githubusercontent.com/93478016/230446546-b485eaf8-3c62-4987-a43b-a9885f99edad.png)

### Documentation

Put the relevant part of the whole use-case diagram "Solution" section of the this issue.

### Additional notes

When we complete the use-case diagrams as a whole team, we will upload them to the wiki as a document.

### Reviewers

Ömer Talip Akalın

### Deadline

06.04.2023 - 23.59

**Comment by ohbahadiroglu** [comment]
@omertalib42 Could you please review the work done ? If everything seems fine you can close the issue.

**Comment by omertalib42** [comment]
LGTM
