### ISSUE TITLE
Adding requirements for "group finding" feature of the platform.

### ISSUE THREAD

**Issue by ohbahadiroglu** [bounswe/bounswe2023group6#63]
### Problem

Group finding feature related requriements needs to be well examined and documented on relevant wiki page.

### Solution

Due to the fact that the group had many questions about the group finding feature and was waiting for the qna session to be made about it, the requirements for this feature were postponed to the next meetings. Since the general lines about this feature were determined during the preparation process of the mockups, the task of documenting the relevant requirements was left for later. Now, group members and I have consolidated well our general ideas regarding this feature. I will document the relevant requirements by looking up the mockups about this feature.

### Documentation

[Requirements page](https://github.com/bounswe/bounswe2023group6/wiki/Requirements)

### Additional notes

- Glossary will be updated after finishing the work.
- The requirements added to the requirements page will be under this issue as comment.

### Reviewers

Ömer Talip Akalın

### Deadline

04.04.2023 - 23.59

**Comment by ohbahadiroglu** [comment]
Added requirements for User-Group interaction.
   * 1.1.3.4.1 Users shall be able to create LFGs.
   * 1.1.3.4.2 Users shall be able to update LFGs.
   * 1.1.3.4.3 Users shall be able to delete LFGs.
   * 1.1.3.4.4 Users shall be able to join groups (via LFG).
   * 1.1.3.4.5 Users shall be able to add details (see 1.2.7) to LFG during the creation.
   * 1.1.3.4.6 Users shall be able to comment on the LFGs.

**Comment by ohbahadiroglu** [comment]
@omertalib42
Could you please review related requirements recently added? If everything is fine you can close the issue.

**Comment by omertalib42** [comment]
Nice work!
