### ISSUE TITLE
Creating Class Diagram About User-Profile-Account

### ISSUE THREAD

**Issue by beyzabektan** [bounswe/bounswe2023group6#70]
### Problem

Class diagram is a UML diagram type that describes a system by visualizing the different types of objects within a system and the relationships among them. For our project, we need to create a class diagram showing the system architecture as a part of our design.

### Solution

We will use Miro for drawing the diagram by referencing the lecture content. We will benefit from object oriented system concepts while creating our classes, showing their properties, methods and relationships between them. While doing that we will take into consideration the attribute visibilities. Once the task is done, the diagram can be accessed via [this link](https://miro.com/app/board/uXjVMVwkHtM=/).

### Additional notes

You can find the related requirements [here](https://github.com/bounswe/bounswe2023group6/wiki/Requirements) under the title of "1.1 User Requirements".

### Reviewers

Ahmet Kudu

### Deadline

06.04.2023-Thursday-23.59

**Comment by beyzabektan** [comment]
@ahmetkudu could you please check and close this issue if it is fine?

**Comment by beyzabektan** [comment]
**The solution is here:**

![class](https://user-images.githubusercontent.com/123978913/230800522-fe3e24d3-a284-4e47-b1fd-8c855fac5eac.jpeg)

**Comment by ahmetkudu** [comment]
That was a nice contribution to the class diagram.
