### ISSUE TITLE
Creating Class Diagram for classes: Feed, Report, Comment, Tags and SearchBar

### ISSUE THREAD

**Issue by ohbahadiroglu** [bounswe/bounswe2023group6#74]
### Problem

The project lacks class diagrams for components like Feed, Report, Comment, Tags, and SearchBar. Class diagrams provide a visual representation of the system's structure and help ensure a shared understanding among team members. Without them, the development process may become inefficient and inconsistent.

### Solution

To address this issue, we propose creating concise class diagrams for the Feed, Report, Comment, Tags, and SearchBar components using Miro. These diagrams will outline attributes, methods, and associations for each class, improving team communication and collaboration during development, and ensuring a cohesive implementation. We will work on collaborative workspace in this [miro link]().

### Additional notes

Once the this task and other tasks of group members are done, the whole diagram can be accessed at [Class Diagrams]() on wiki.

### Reviewers

Ömer Bahadıroğlu, Ömer Talip Akalın, Süleyman Melih Portakal

### Deadline

06.04.2023 - 23:59

**Comment by omertalib42** [comment]
We've reviewed this section with the whole team during #76 (links to be added). Although it's almost finished, let's keep this up a bit longer as we're not completely finalized it.

**Comment by omertalib42** [comment]
It's done.
