### ISSUE TITLE
Adding Meeting Notes #12

### ISSUE THREAD

**Issue by omertalib42** [bounswe/bounswe2023group6#76]
### Problem

As a part of our daily meetings to complete the milestone on time, I was the note taker of this meeting. 
They need to be edited and added to our wiki.

### Reviewers

Ömer Talip Akalın, Sena Özpınar

### Deadline

09.01.2023 - 23.59

**Comment by omertalib42** [comment]
Notes are added and can be viewed [here](https://github.com/bounswe/bounswe2023group6/wiki/Meeting-Notes-%2312---06.04.2023).

@senaozpinar (or anyone who's available), you can review and close the issue

**Comment by senaozpinar** [comment]
Meeting notes are reviewed.
