### ISSUE TITLE
Revision of the Use Case Diagram of the Profile Page

### ISSUE THREAD

**Issue by Legervad** [bounswe/bounswe2023group6#78]
### Problem

The use case diagram of the profile page had not meet the requirements, thus needed revision.

### Solution

- Making distinction between viewing own profile page and viewing some other's
- Posts, events, and LFGs owned by the user now can be seen in their profile page. Therefore, the use case diagram should be adapted to the changes

### Documentation

All changes can be seen on the [miro page](https://miro.com/app/board/uXjVMX21m00=/)

### Additional notes

Here's the old version

> ![image](https://user-images.githubusercontent.com/74266381/230643633-7a3fbc9f-8408-4c85-80c5-df1750661eaf.png)

Here's the updated version

> ![image](https://user-images.githubusercontent.com/74266381/230643700-a00c6220-46b3-4241-aa6f-304d0049d830.png)

### Reviewers

Beyzanur Bektan

### Deadline

07.04.2023 - Friday - 23.59

**Comment by erkamkavak** [comment]
I checked it and it seems nice.
