### ISSUE TITLE
Adding Meeting Notes #13

### ISSUE THREAD

**Issue by huscivi** [bounswe/bounswe2023group6#80]
### Problem

I took the notes of this meeting as part of our daily meetings.
Notes I take need to be added to our wiki page.

### Documentation

[Meeting Notes #13](https://github.com/bounswe/bounswe2023group6/wiki/Meeting-Notes-%2313---07.04.2023)

### Reviewers

Ömer Bahadıroğlu

### Deadline

08.04.2023

**Comment by huscivi** [comment]
@ohbahadiroglu could you review my study?

**Comment by ohbahadiroglu** [comment]
I reviewed [Meeting Notes #13](https://github.com/bounswe/bounswe2023group6/wiki/Meeting-Notes-%2313---07.04.2023) that you prepared, all sections includes necesarry notes. I see that you explained everything about meeting really well. I just want to make one point that you can add related issues of group members to the action items table. Or you can ask for people to add related issues link for their issues. These are all I can say. Altough, I will close the issue as it is done.
