### ISSUE TITLE
Creation of the Sequence Diagram for Creating and Editing Comment

### ISSUE THREAD

**Issue by huscivi** [bounswe/bounswe2023group6#82]
### Problem

The sequence diagram for the creating and editing comment should be implemented as decided on the 13th meeting.

### Reviewers

Ömer Bahadıroğlu

### Deadline

08.04.2023 - Saturday - 21:00

**Comment by huscivi** [comment]
![sequenceDiagram](https://user-images.githubusercontent.com/113240964/230762277-f7e3f65f-9af8-4380-a402-d11029024c6c.png)

**Comment by huscivi** [comment]
@ohbahadiroglu could you review my study?

**Comment by ohbahadiroglu** [comment]
Seems enough. I will close the issue since we have strict deadline for deliverables.
