### ISSUE TITLE
Forming sequence diagrams for Search & Filter

### ISSUE THREAD

**Issue by omertalib42** [bounswe/bounswe2023group6#84]
### Problem

We will be creating a sequence diagram to help visualize and understand the interactions and data flow within the system. This diagram will focus on the search and filter functionality, detailing how users can search and filter various entities within the application. 

### Solution

Creating a sequence diagram.

### Additional notes

Me and @erkamkavak have been assigned to the issue together.

### Reviewers

Sena Özpınar

### Deadline

08.04.2023 - 23:59

**Comment by erkamkavak** [comment]
Searchbar sequence diagram is put below. 
* When user activates searchbar, searchbar requires user to select search types. User selects the search types(these search types are sent to searchbar) 
* When user searches a query, searchbar sends the query with the search types to the searchbar service. Searchbar service then calls the corresponding methods for each selected search type. 
* After calling methods, searchbar service returns the list of results to the searchbar and searchbar returns this list of results to the user. 
* User can also sort results based on filters. 

![image](https://user-images.githubusercontent.com/70749779/230791210-68c13b79-ec36-49d5-a09d-c50187bae06b.png)

**Comment by erkamkavak** [comment]
@senaozpinar Can you review and close this issue?

**Comment by senaozpinar** [comment]
@omertalib42  This issue has been reviewed.
