### ISSUE TITLE
Forming sequence diagrams for Admin

### ISSUE THREAD

**Issue by omertalib42** [bounswe/bounswe2023group6#85]
### Problem

We will be creating a sequence diagram to help visualize and understand the interactions and data flow within the system. We will concentrate on the interactions between the admin user and the system, showcasing the different administrative tasks and their effect on the system.

### Solution

Creating admin sequence diagram.

### Additional notes

Me and @erkamkavak have been assigned to the issue together.

### Reviewers

Sena Özpınar

### Deadline

08.04.2023 - 23:59

**Comment by erkamkavak** [comment]
Admin sequence diagram is put below. Admin can ban user, unban user or delete content. 
* Admin selects the user to ban or unban and its id is sent to user service. User service then updates database for corresponding user and then returns.
* Admin selects the content to delete and its id is sent to content service. Content service then updates database for corresponding content and then returns.  

![image](https://user-images.githubusercontent.com/70749779/230791225-d53ad2f2-e29e-40fb-8e04-0554e7ad062f.png)

**Comment by erkamkavak** [comment]
@senaozpinar Can you review and close this issue?

**Comment by senaozpinar** [comment]
@ this issue has been reviewed.
