### ISSUE TITLE
Writing status of deliverables 3,4 and 5 for milestone report

### ISSUE THREAD

**Issue by smelihportakal** [bounswe/bounswe2023group6#92]
### Problem

We need to prepare a milestone report that gathers the major deliverables related to the requirements, design, and plan of our project. Our milestone report must include evaluation of the status of deliverables.

### Solution

We will prepare our report in google doc. I will write evaluation of the status of deliverables 3,4 and 5 which are:
* Software design documents in UML: use case, class, and sequence diagrams
* Project plan, RAM (responsibility assignment matrix), and Communication plan
* Milestone report

### Documentation

[milestone report](https://github.com/bounswe/bounswe2023group6/wiki/Milestone-1-Report#d5-milestone-report)

### Deadline

09.04.2023 - 23.59 - Sunday

**Comment by smelihportakal** [comment]
@umutdmr Can you review and close this issue?

**Comment by umutdmr** [comment]
I reviewed the related parts of the milestone, read it carefully and it looks correct. So I can close this issue as completed.
