### ISSUE TITLE
Forming a sequence diagram for Event creation and Event Editing

### ISSUE THREAD

**Issue by ohbahadiroglu** [bounswe/bounswe2023group6#94]
### Problem

Sequence Diagrams are interaction diagrams that detail how operations are carried out. They capture the interaction between objects in the context of a collaboration. Sequence Diagrams are time focus and they show the order of the interaction visually by using the vertical axis of the diagram to represent time what messages are sent and when. For these purpose, our project needs Event creation and Event Editing sequence diagrams separately. 

### Solution

I will be forming Event creation and event editing sequence diagrams separately in our Miro workspace which we use to form diagrams. 

### Documentation

Solution will be in our sequence diagrams page on wiki.

### Additional notes

- Work done for this issue will be added as comments under this issue.
- Actually the task assigned to me was taken care of before the issue deadline by me, but the issue about it opened after completing task. The reason is that we're trying to catch the deadline as whole team. That is why this kind of ambiguity happen.

### Reviewers

Ömer Talip Akalın

### Deadline

08.04.2023 - 23:59

**Comment by ohbahadiroglu** [comment]
## Create Event - Sequence Diagram
![Create Event](https://user-images.githubusercontent.com/93478016/230778747-b92a2b73-338a-42b0-abce-1dd06f058235.jpg)
## Edit Event - Sequence Diagram
![Edit Event](https://user-images.githubusercontent.com/93478016/230778748-fd808c6f-ae84-40e1-b3fe-debf03f55f57.jpg)

**Comment by ohbahadiroglu** [comment]
@omertalib42 I know that you gave me a valuable feedback about discarding Event and Repository layers in the [Meeting #14 - 08.04.2023](https://github.com/bounswe/bounswe2023group6/wiki/Meeting-Notes-%2314---08.04.2023). I was thinking to discard those layers since your feedback seemed logical to me, but in the end, I decided to keep those layers because of staff's answer given in the discord after your question about these cases. I hope everything is ok with your side and you can close the issue as it is done. Thanks.

**Comment by omertalib42** [comment]
Let's discuss in the meeting today shortly :)
